// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/cmd.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登陆消息
type Game_C_TokenLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	MachineID            string   `protobuf:"bytes,2,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_TokenLogin) Reset()         { *m = Game_C_TokenLogin{} }
func (m *Game_C_TokenLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_TokenLogin) ProtoMessage()    {}
func (*Game_C_TokenLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{0}
}

func (m *Game_C_TokenLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_TokenLogin.Unmarshal(m, b)
}
func (m *Game_C_TokenLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_TokenLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_TokenLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_TokenLogin.Merge(m, src)
}
func (m *Game_C_TokenLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_TokenLogin.Size(m)
}
func (m *Game_C_TokenLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_TokenLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_TokenLogin proto.InternalMessageInfo

func (m *Game_C_TokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Game_C_TokenLogin) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

//用户起立
type Game_C_UserStandUp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserStandUp) Reset()         { *m = Game_C_UserStandUp{} }
func (m *Game_C_UserStandUp) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserStandUp) ProtoMessage()    {}
func (*Game_C_UserStandUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{1}
}

func (m *Game_C_UserStandUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserStandUp.Unmarshal(m, b)
}
func (m *Game_C_UserStandUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserStandUp.Marshal(b, m, deterministic)
}
func (m *Game_C_UserStandUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserStandUp.Merge(m, src)
}
func (m *Game_C_UserStandUp) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserStandUp.Size(m)
}
func (m *Game_C_UserStandUp) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserStandUp.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserStandUp proto.InternalMessageInfo

//用户下注
type Game_C_UserJetton struct {
	JettonAreaAndSocre   map[int32]float32 `protobuf:"bytes,1,rep,name=JettonAreaAndSocre,proto3" json:"JettonAreaAndSocre,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Game_C_UserJetton) Reset()         { *m = Game_C_UserJetton{} }
func (m *Game_C_UserJetton) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserJetton) ProtoMessage()    {}
func (*Game_C_UserJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{2}
}

func (m *Game_C_UserJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserJetton.Unmarshal(m, b)
}
func (m *Game_C_UserJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserJetton.Marshal(b, m, deterministic)
}
func (m *Game_C_UserJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserJetton.Merge(m, src)
}
func (m *Game_C_UserJetton) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserJetton.Size(m)
}
func (m *Game_C_UserJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserJetton proto.InternalMessageInfo

func (m *Game_C_UserJetton) GetJettonAreaAndSocre() map[int32]float32 {
	if m != nil {
		return m.JettonAreaAndSocre
	}
	return nil
}

//比较大小
type Game_C_UserCompare struct {
	JettonArea           int32    `protobuf:"varint,1,opt,name=JettonArea,proto3" json:"JettonArea,omitempty"`
	JettonSocre          float32  `protobuf:"fixed32,2,opt,name=JettonSocre,proto3" json:"JettonSocre,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserCompare) Reset()         { *m = Game_C_UserCompare{} }
func (m *Game_C_UserCompare) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserCompare) ProtoMessage()    {}
func (*Game_C_UserCompare) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{3}
}

func (m *Game_C_UserCompare) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserCompare.Unmarshal(m, b)
}
func (m *Game_C_UserCompare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserCompare.Marshal(b, m, deterministic)
}
func (m *Game_C_UserCompare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserCompare.Merge(m, src)
}
func (m *Game_C_UserCompare) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserCompare.Size(m)
}
func (m *Game_C_UserCompare) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserCompare.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserCompare proto.InternalMessageInfo

func (m *Game_C_UserCompare) GetJettonArea() int32 {
	if m != nil {
		return m.JettonArea
	}
	return 0
}

func (m *Game_C_UserCompare) GetJettonSocre() float32 {
	if m != nil {
		return m.JettonSocre
	}
	return 0
}

//获取用户列表 分页
type Game_C_UserList struct {
	Page                 int32    `protobuf:"varint,1,opt,name=Page,proto3" json:"Page,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=Size,proto3" json:"Size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserList) Reset()         { *m = Game_C_UserList{} }
func (m *Game_C_UserList) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserList) ProtoMessage()    {}
func (*Game_C_UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{4}
}

func (m *Game_C_UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserList.Unmarshal(m, b)
}
func (m *Game_C_UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserList.Marshal(b, m, deterministic)
}
func (m *Game_C_UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserList.Merge(m, src)
}
func (m *Game_C_UserList) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserList.Size(m)
}
func (m *Game_C_UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserList proto.InternalMessageInfo

func (m *Game_C_UserList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Game_C_UserList) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

//请求失败
type Game_S_ReqlyFail struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_ReqlyFail) Reset()         { *m = Game_S_ReqlyFail{} }
func (m *Game_S_ReqlyFail) String() string { return proto.CompactTextString(m) }
func (*Game_S_ReqlyFail) ProtoMessage()    {}
func (*Game_S_ReqlyFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{5}
}

func (m *Game_S_ReqlyFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_ReqlyFail.Unmarshal(m, b)
}
func (m *Game_S_ReqlyFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_ReqlyFail.Marshal(b, m, deterministic)
}
func (m *Game_S_ReqlyFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_ReqlyFail.Merge(m, src)
}
func (m *Game_S_ReqlyFail) XXX_Size() int {
	return xxx_messageInfo_Game_S_ReqlyFail.Size(m)
}
func (m *Game_S_ReqlyFail) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_ReqlyFail.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_ReqlyFail proto.InternalMessageInfo

func (m *Game_S_ReqlyFail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Game_S_ReqlyFail) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

//登陆成功
type Game_S_LoginSuccess struct {
	TableID              int32    `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LoginSuccess) Reset()         { *m = Game_S_LoginSuccess{} }
func (m *Game_S_LoginSuccess) String() string { return proto.CompactTextString(m) }
func (*Game_S_LoginSuccess) ProtoMessage()    {}
func (*Game_S_LoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{6}
}

func (m *Game_S_LoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LoginSuccess.Unmarshal(m, b)
}
func (m *Game_S_LoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LoginSuccess.Marshal(b, m, deterministic)
}
func (m *Game_S_LoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LoginSuccess.Merge(m, src)
}
func (m *Game_S_LoginSuccess) XXX_Size() int {
	return xxx_messageInfo_Game_S_LoginSuccess.Size(m)
}
func (m *Game_S_LoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LoginSuccess proto.InternalMessageInfo

func (m *Game_S_LoginSuccess) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

//铃铛结果
type Game_S_GameResult struct {
	LotteryResults       []int32   `protobuf:"varint,1,rep,packed,name=LotteryResults,proto3" json:"LotteryResults,omitempty"`
	WinArea              []float32 `protobuf:"fixed32,2,rep,packed,name=WinArea,proto3" json:"WinArea,omitempty"`
	UserGoldCoin         float32   `protobuf:"fixed32,3,opt,name=UserGoldCoin,proto3" json:"UserGoldCoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Game_S_GameResult) Reset()         { *m = Game_S_GameResult{} }
func (m *Game_S_GameResult) String() string { return proto.CompactTextString(m) }
func (*Game_S_GameResult) ProtoMessage()    {}
func (*Game_S_GameResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{7}
}

func (m *Game_S_GameResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GameResult.Unmarshal(m, b)
}
func (m *Game_S_GameResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GameResult.Marshal(b, m, deterministic)
}
func (m *Game_S_GameResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GameResult.Merge(m, src)
}
func (m *Game_S_GameResult) XXX_Size() int {
	return xxx_messageInfo_Game_S_GameResult.Size(m)
}
func (m *Game_S_GameResult) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GameResult.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GameResult proto.InternalMessageInfo

func (m *Game_S_GameResult) GetLotteryResults() []int32 {
	if m != nil {
		return m.LotteryResults
	}
	return nil
}

func (m *Game_S_GameResult) GetWinArea() []float32 {
	if m != nil {
		return m.WinArea
	}
	return nil
}

func (m *Game_S_GameResult) GetUserGoldCoin() float32 {
	if m != nil {
		return m.UserGoldCoin
	}
	return 0
}

// 比大小结果
type Game_S_CompareResult struct {
	LotteryResults       int32    `protobuf:"varint,1,opt,name=LotteryResults,proto3" json:"LotteryResults,omitempty"`
	UserGoldCoin         float32  `protobuf:"fixed32,2,opt,name=UserGoldCoin,proto3" json:"UserGoldCoin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_CompareResult) Reset()         { *m = Game_S_CompareResult{} }
func (m *Game_S_CompareResult) String() string { return proto.CompactTextString(m) }
func (*Game_S_CompareResult) ProtoMessage()    {}
func (*Game_S_CompareResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{8}
}

func (m *Game_S_CompareResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_CompareResult.Unmarshal(m, b)
}
func (m *Game_S_CompareResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_CompareResult.Marshal(b, m, deterministic)
}
func (m *Game_S_CompareResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_CompareResult.Merge(m, src)
}
func (m *Game_S_CompareResult) XXX_Size() int {
	return xxx_messageInfo_Game_S_CompareResult.Size(m)
}
func (m *Game_S_CompareResult) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_CompareResult.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_CompareResult proto.InternalMessageInfo

func (m *Game_S_CompareResult) GetLotteryResults() int32 {
	if m != nil {
		return m.LotteryResults
	}
	return 0
}

func (m *Game_S_CompareResult) GetUserGoldCoin() float32 {
	if m != nil {
		return m.UserGoldCoin
	}
	return 0
}

//user
type Game_S_User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	UserGold             float32  `protobuf:"fixed32,3,opt,name=UserGold,proto3" json:"UserGold,omitempty"`
	UserDiamond          float32  `protobuf:"fixed32,4,opt,name=UserDiamond,proto3" json:"UserDiamond,omitempty"`
	MemberOrder          int32    `protobuf:"varint,5,opt,name=MemberOrder,proto3" json:"MemberOrder,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,6,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl,omitempty"`
	FaceID               int32    `protobuf:"varint,7,opt,name=FaceID,proto3" json:"FaceID,omitempty"`
	RoleID               int32    `protobuf:"varint,8,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	SuitID               int32    `protobuf:"varint,9,opt,name=SuitID,proto3" json:"SuitID,omitempty"`
	PhotoFrameID         int32    `protobuf:"varint,10,opt,name=PhotoFrameID,proto3" json:"PhotoFrameID,omitempty"`
	TableID              int32    `protobuf:"varint,11,opt,name=TableID,proto3" json:"TableID,omitempty"`
	ChairID              int32    `protobuf:"varint,12,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	Gender               int32    `protobuf:"varint,14,opt,name=Gender,proto3" json:"Gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_User) Reset()         { *m = Game_S_User{} }
func (m *Game_S_User) String() string { return proto.CompactTextString(m) }
func (*Game_S_User) ProtoMessage()    {}
func (*Game_S_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{9}
}

func (m *Game_S_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_User.Unmarshal(m, b)
}
func (m *Game_S_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_User.Marshal(b, m, deterministic)
}
func (m *Game_S_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_User.Merge(m, src)
}
func (m *Game_S_User) XXX_Size() int {
	return xxx_messageInfo_Game_S_User.Size(m)
}
func (m *Game_S_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_User.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_User proto.InternalMessageInfo

func (m *Game_S_User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_S_User) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *Game_S_User) GetUserGold() float32 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *Game_S_User) GetUserDiamond() float32 {
	if m != nil {
		return m.UserDiamond
	}
	return 0
}

func (m *Game_S_User) GetMemberOrder() int32 {
	if m != nil {
		return m.MemberOrder
	}
	return 0
}

func (m *Game_S_User) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *Game_S_User) GetFaceID() int32 {
	if m != nil {
		return m.FaceID
	}
	return 0
}

func (m *Game_S_User) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *Game_S_User) GetSuitID() int32 {
	if m != nil {
		return m.SuitID
	}
	return 0
}

func (m *Game_S_User) GetPhotoFrameID() int32 {
	if m != nil {
		return m.PhotoFrameID
	}
	return 0
}

func (m *Game_S_User) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_S_User) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Game_S_User) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

// 返回用户列表数据
type Game_S_UserList struct {
	Data                 []*Game_S_TempUser `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Game_S_UserList) Reset()         { *m = Game_S_UserList{} }
func (m *Game_S_UserList) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserList) ProtoMessage()    {}
func (*Game_S_UserList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{10}
}

func (m *Game_S_UserList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserList.Unmarshal(m, b)
}
func (m *Game_S_UserList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserList.Marshal(b, m, deterministic)
}
func (m *Game_S_UserList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserList.Merge(m, src)
}
func (m *Game_S_UserList) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserList.Size(m)
}
func (m *Game_S_UserList) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserList.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserList proto.InternalMessageInfo

func (m *Game_S_UserList) GetData() []*Game_S_TempUser {
	if m != nil {
		return m.Data
	}
	return nil
}

type Game_S_TempUser struct {
	User                 *Game_S_User `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game_S_TempUser) Reset()         { *m = Game_S_TempUser{} }
func (m *Game_S_TempUser) String() string { return proto.CompactTextString(m) }
func (*Game_S_TempUser) ProtoMessage()    {}
func (*Game_S_TempUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{11}
}

func (m *Game_S_TempUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_TempUser.Unmarshal(m, b)
}
func (m *Game_S_TempUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_TempUser.Marshal(b, m, deterministic)
}
func (m *Game_S_TempUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_TempUser.Merge(m, src)
}
func (m *Game_S_TempUser) XXX_Size() int {
	return xxx_messageInfo_Game_S_TempUser.Size(m)
}
func (m *Game_S_TempUser) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_TempUser.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_TempUser proto.InternalMessageInfo

func (m *Game_S_TempUser) GetUser() *Game_S_User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*Game_C_TokenLogin)(nil), "msg.Game_C_TokenLogin")
	proto.RegisterType((*Game_C_UserStandUp)(nil), "msg.Game_C_UserStandUp")
	proto.RegisterType((*Game_C_UserJetton)(nil), "msg.Game_C_UserJetton")
	proto.RegisterMapType((map[int32]float32)(nil), "msg.Game_C_UserJetton.JettonAreaAndSocreEntry")
	proto.RegisterType((*Game_C_UserCompare)(nil), "msg.Game_C_UserCompare")
	proto.RegisterType((*Game_C_UserList)(nil), "msg.Game_C_UserList")
	proto.RegisterType((*Game_S_ReqlyFail)(nil), "msg.Game_S_ReqlyFail")
	proto.RegisterType((*Game_S_LoginSuccess)(nil), "msg.Game_S_LoginSuccess")
	proto.RegisterType((*Game_S_GameResult)(nil), "msg.Game_S_GameResult")
	proto.RegisterType((*Game_S_CompareResult)(nil), "msg.Game_S_CompareResult")
	proto.RegisterType((*Game_S_User)(nil), "msg.Game_S_User")
	proto.RegisterType((*Game_S_UserList)(nil), "msg.Game_S_UserList")
	proto.RegisterType((*Game_S_TempUser)(nil), "msg.Game_S_TempUser")
}

func init() { proto.RegisterFile("msg/cmd.proto", fileDescriptor_a090769f8e2c12a2) }

var fileDescriptor_a090769f8e2c12a2 = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xcb, 0x6e, 0xdb, 0x3a,
	0x10, 0x85, 0x5f, 0x79, 0x8c, 0x93, 0xdc, 0x5c, 0xd6, 0x68, 0x85, 0xa0, 0x28, 0x0c, 0xa1, 0x28,
	0xbc, 0x72, 0x80, 0x74, 0xd1, 0xd7, 0x2a, 0xb0, 0x13, 0x37, 0x85, 0x93, 0x06, 0x52, 0xd2, 0xee,
	0x6a, 0xd0, 0xd2, 0x40, 0x11, 0x22, 0x8a, 0x2e, 0x45, 0x17, 0x70, 0xff, 0xa3, 0x3f, 0xd3, 0xaf,
	0x2b, 0x86, 0xa4, 0x6c, 0x39, 0x71, 0xbb, 0x31, 0x79, 0xce, 0x70, 0xce, 0xf1, 0xcc, 0x50, 0x84,
	0x7d, 0x51, 0x24, 0xc7, 0x91, 0x88, 0xfb, 0x33, 0x25, 0xb5, 0x64, 0x0d, 0x51, 0x24, 0xfe, 0x08,
	0xfe, 0x1f, 0x71, 0x81, 0x93, 0xc1, 0xe4, 0x46, 0xde, 0x63, 0x3e, 0x96, 0x49, 0x9a, 0xb3, 0x0e,
	0xb4, 0x0c, 0xf2, 0x6a, 0xdd, 0x5a, 0x6f, 0x37, 0xb0, 0x80, 0x3d, 0x87, 0xdd, 0x4b, 0x1e, 0xdd,
	0xa5, 0x39, 0x5e, 0x0c, 0xbd, 0xba, 0x89, 0xac, 0x08, 0xbf, 0x03, 0xcc, 0x09, 0xdd, 0x16, 0xa8,
	0x42, 0xcd, 0xf3, 0xf8, 0x76, 0xe6, 0xff, 0xae, 0x2d, 0xf5, 0x89, 0xfe, 0x84, 0x5a, 0xcb, 0x9c,
	0x7d, 0x03, 0x66, 0x77, 0xa7, 0x0a, 0xf9, 0x69, 0x1e, 0x87, 0x32, 0x52, 0xe8, 0xd5, 0xba, 0x8d,
	0x5e, 0xfb, 0xa4, 0xdf, 0x17, 0x45, 0xd2, 0x7f, 0x94, 0xd3, 0x7f, 0x9c, 0x70, 0x96, 0x6b, 0xb5,
	0x08, 0x36, 0x28, 0x1d, 0x9d, 0xc1, 0xb3, 0xbf, 0x1c, 0x67, 0x87, 0xd0, 0xb8, 0xc7, 0x85, 0x29,
	0xac, 0x15, 0xd0, 0x96, 0x8a, 0xfd, 0xc1, 0xb3, 0x39, 0x9a, 0x92, 0xea, 0x81, 0x05, 0xef, 0xeb,
	0x6f, 0x6b, 0xfe, 0x97, 0xb5, 0x92, 0x06, 0x52, 0xcc, 0xb8, 0x42, 0xf6, 0x02, 0x60, 0x25, 0xee,
	0x84, 0x2a, 0x0c, 0xeb, 0x42, 0xdb, 0x22, 0x5b, 0x95, 0x55, 0xad, 0x52, 0xfe, 0x3b, 0xf8, 0xaf,
	0xa2, 0x3b, 0x4e, 0x0b, 0xcd, 0x18, 0x34, 0xaf, 0x79, 0x82, 0x4e, 0xce, 0xec, 0x89, 0x0b, 0xd3,
	0x9f, 0x56, 0xa1, 0x15, 0x98, 0xbd, 0x3f, 0x86, 0x43, 0x93, 0x1a, 0x4e, 0x02, 0xfc, 0x9e, 0x2d,
	0xce, 0x79, 0x9a, 0xd1, 0x5c, 0xce, 0x94, 0x92, 0x6a, 0x20, 0xe3, 0x52, 0x60, 0x45, 0xb0, 0x23,
	0xd8, 0x31, 0xe0, 0xb2, 0x48, 0xdc, 0xd0, 0x96, 0xd8, 0x3f, 0x86, 0x27, 0x4e, 0xcd, 0xcc, 0x3d,
	0x9c, 0x47, 0x11, 0x16, 0x05, 0xf3, 0x60, 0xfb, 0x86, 0x4f, 0x33, 0x1a, 0xb3, 0x95, 0x2b, 0xa1,
	0xbf, 0x70, 0xd3, 0x0c, 0x27, 0xb4, 0x04, 0x58, 0xcc, 0x33, 0xcd, 0x5e, 0xc1, 0xc1, 0x58, 0x6a,
	0x8d, 0x6a, 0x61, 0x89, 0xc2, 0x4c, 0xb2, 0x15, 0x3c, 0x60, 0x49, 0xf6, 0x6b, 0x6a, 0xbb, 0x56,
	0xef, 0x36, 0x7a, 0xf5, 0xa0, 0x84, 0xcc, 0x87, 0x3d, 0xea, 0xc4, 0x48, 0x66, 0xf1, 0x40, 0xa6,
	0xb9, 0xd7, 0x30, 0x3d, 0x5b, 0xe3, 0xfc, 0x29, 0x74, 0x9c, 0xb5, 0x1b, 0xc4, 0x3f, 0xdc, 0x6b,
	0x1b, 0xdc, 0x1f, 0x7a, 0xd4, 0x37, 0x78, 0xfc, 0x6a, 0x40, 0xdb, 0x99, 0x10, 0xcf, 0x9e, 0xc2,
	0x16, 0xad, 0xcb, 0x3e, 0x38, 0x44, 0x3d, 0xbd, 0x4a, 0xef, 0xf1, 0x8a, 0x0b, 0x2c, 0x7b, 0x5a,
	0x62, 0x8a, 0x95, 0x9a, 0xae, 0x8e, 0x25, 0xa6, 0xab, 0x41, 0xfb, 0x61, 0xca, 0x85, 0xcc, 0x63,
	0xaf, 0x69, 0xaf, 0x46, 0x85, 0xa2, 0x13, 0x97, 0x28, 0xa6, 0xa8, 0x3e, 0xab, 0x18, 0x95, 0xd7,
	0x32, 0xb6, 0x55, 0x8a, 0xea, 0xf8, 0x88, 0x3c, 0xbe, 0x10, 0x3c, 0xc1, 0x5b, 0x95, 0x79, 0x5b,
	0xc6, 0x7f, 0x8d, 0xa3, 0xff, 0x7d, 0xce, 0x23, 0x9a, 0xdf, 0xb6, 0xfd, 0xdf, 0x16, 0x11, 0x1f,
	0x48, 0x33, 0xd7, 0x1d, 0xcb, 0x5b, 0x44, 0x7c, 0x38, 0x4f, 0xf5, 0xc5, 0xd0, 0xdb, 0xb5, 0xbc,
	0x45, 0xe4, 0x75, 0x7d, 0x27, 0xb5, 0x3c, 0x57, 0x5c, 0x50, 0x16, 0x98, 0xe8, 0x1a, 0x57, 0xbd,
	0x2c, 0xed, 0xb5, 0xcb, 0x42, 0x91, 0xc1, 0x1d, 0x4f, 0xa9, 0x7d, 0x7b, 0x36, 0xe2, 0xa0, 0xf1,
	0xd3, 0x5c, 0xcf, 0x0b, 0x6f, 0xdf, 0xf9, 0x19, 0x44, 0xfc, 0x08, 0x73, 0x2a, 0xfc, 0xc0, 0xf2,
	0x16, 0xf9, 0x1f, 0xdc, 0x07, 0x13, 0xae, 0x3e, 0x98, 0x1e, 0x34, 0x87, 0x5c, 0x73, 0xf7, 0x68,
	0x74, 0x56, 0x8f, 0x46, 0x38, 0xb9, 0x41, 0x31, 0xa3, 0x73, 0x81, 0x39, 0xe1, 0xbf, 0x59, 0x26,
	0x97, 0x01, 0xf6, 0x12, 0x9a, 0xb4, 0x9a, 0xa9, 0xb6, 0x4f, 0x0e, 0xab, 0xc9, 0x36, 0x91, 0x7e,
	0xa7, 0x5b, 0xe6, 0x99, 0x7c, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xe6, 0x03, 0x2c, 0x37,
	0x05, 0x00, 0x00,
}
