// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/cmd.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登陆消息
type Game_C_TokenLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	MachineID            string   `protobuf:"bytes,2,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_TokenLogin) Reset()         { *m = Game_C_TokenLogin{} }
func (m *Game_C_TokenLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_TokenLogin) ProtoMessage()    {}
func (*Game_C_TokenLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{0}
}

func (m *Game_C_TokenLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_TokenLogin.Unmarshal(m, b)
}
func (m *Game_C_TokenLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_TokenLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_TokenLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_TokenLogin.Merge(m, src)
}
func (m *Game_C_TokenLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_TokenLogin.Size(m)
}
func (m *Game_C_TokenLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_TokenLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_TokenLogin proto.InternalMessageInfo

func (m *Game_C_TokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Game_C_TokenLogin) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

//机器人登陆
type Game_C_RobotLogin struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BatchID              int32    `protobuf:"varint,2,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_RobotLogin) Reset()         { *m = Game_C_RobotLogin{} }
func (m *Game_C_RobotLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_RobotLogin) ProtoMessage()    {}
func (*Game_C_RobotLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{1}
}

func (m *Game_C_RobotLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_RobotLogin.Unmarshal(m, b)
}
func (m *Game_C_RobotLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_RobotLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_RobotLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_RobotLogin.Merge(m, src)
}
func (m *Game_C_RobotLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_RobotLogin.Size(m)
}
func (m *Game_C_RobotLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_RobotLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_RobotLogin proto.InternalMessageInfo

func (m *Game_C_RobotLogin) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_C_RobotLogin) GetBatchID() int32 {
	if m != nil {
		return m.BatchID
	}
	return 0
}

//用户坐下
type Game_C_UserSitDown struct {
	TableID              int32    `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
	ChairID              int32    `protobuf:"varint,2,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserSitDown) Reset()         { *m = Game_C_UserSitDown{} }
func (m *Game_C_UserSitDown) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserSitDown) ProtoMessage()    {}
func (*Game_C_UserSitDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{2}
}

func (m *Game_C_UserSitDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserSitDown.Unmarshal(m, b)
}
func (m *Game_C_UserSitDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserSitDown.Marshal(b, m, deterministic)
}
func (m *Game_C_UserSitDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserSitDown.Merge(m, src)
}
func (m *Game_C_UserSitDown) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserSitDown.Size(m)
}
func (m *Game_C_UserSitDown) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserSitDown.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserSitDown proto.InternalMessageInfo

func (m *Game_C_UserSitDown) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_C_UserSitDown) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//用户起立
type Game_C_UserStandUp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserStandUp) Reset()         { *m = Game_C_UserStandUp{} }
func (m *Game_C_UserStandUp) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserStandUp) ProtoMessage()    {}
func (*Game_C_UserStandUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{3}
}

func (m *Game_C_UserStandUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserStandUp.Unmarshal(m, b)
}
func (m *Game_C_UserStandUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserStandUp.Marshal(b, m, deterministic)
}
func (m *Game_C_UserStandUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserStandUp.Merge(m, src)
}
func (m *Game_C_UserStandUp) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserStandUp.Size(m)
}
func (m *Game_C_UserStandUp) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserStandUp.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserStandUp proto.InternalMessageInfo

//用户开炮
type Game_C_UserFire struct {
	BulletType           int32    `protobuf:"varint,1,opt,name=BulletType,proto3" json:"BulletType,omitempty"`
	BulletAngle          int32    `protobuf:"varint,2,opt,name=BulletAngle,proto3" json:"BulletAngle,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserFire) Reset()         { *m = Game_C_UserFire{} }
func (m *Game_C_UserFire) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserFire) ProtoMessage()    {}
func (*Game_C_UserFire) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{4}
}

func (m *Game_C_UserFire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserFire.Unmarshal(m, b)
}
func (m *Game_C_UserFire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserFire.Marshal(b, m, deterministic)
}
func (m *Game_C_UserFire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserFire.Merge(m, src)
}
func (m *Game_C_UserFire) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserFire.Size(m)
}
func (m *Game_C_UserFire) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserFire.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserFire proto.InternalMessageInfo

func (m *Game_C_UserFire) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

func (m *Game_C_UserFire) GetBulletAngle() int32 {
	if m != nil {
		return m.BulletAngle
	}
	return 0
}

//捕获消息
type Game_C_CatchFish struct {
	BulletID             int32    `protobuf:"varint,1,opt,name=BulletID,proto3" json:"BulletID,omitempty"`
	FishID               int32    `protobuf:"varint,2,opt,name=FishID,proto3" json:"FishID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_CatchFish) Reset()         { *m = Game_C_CatchFish{} }
func (m *Game_C_CatchFish) String() string { return proto.CompactTextString(m) }
func (*Game_C_CatchFish) ProtoMessage()    {}
func (*Game_C_CatchFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{5}
}

func (m *Game_C_CatchFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_CatchFish.Unmarshal(m, b)
}
func (m *Game_C_CatchFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_CatchFish.Marshal(b, m, deterministic)
}
func (m *Game_C_CatchFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_CatchFish.Merge(m, src)
}
func (m *Game_C_CatchFish) XXX_Size() int {
	return xxx_messageInfo_Game_C_CatchFish.Size(m)
}
func (m *Game_C_CatchFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_CatchFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_CatchFish proto.InternalMessageInfo

func (m *Game_C_CatchFish) GetBulletID() int32 {
	if m != nil {
		return m.BulletID
	}
	return 0
}

func (m *Game_C_CatchFish) GetFishID() int32 {
	if m != nil {
		return m.FishID
	}
	return 0
}

//用户变炮
type Game_C_ChangeBullet struct {
	BulletType           int32    `protobuf:"varint,1,opt,name=BulletType,proto3" json:"BulletType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_ChangeBullet) Reset()         { *m = Game_C_ChangeBullet{} }
func (m *Game_C_ChangeBullet) String() string { return proto.CompactTextString(m) }
func (*Game_C_ChangeBullet) ProtoMessage()    {}
func (*Game_C_ChangeBullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{6}
}

func (m *Game_C_ChangeBullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_ChangeBullet.Unmarshal(m, b)
}
func (m *Game_C_ChangeBullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_ChangeBullet.Marshal(b, m, deterministic)
}
func (m *Game_C_ChangeBullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_ChangeBullet.Merge(m, src)
}
func (m *Game_C_ChangeBullet) XXX_Size() int {
	return xxx_messageInfo_Game_C_ChangeBullet.Size(m)
}
func (m *Game_C_ChangeBullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_ChangeBullet.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_ChangeBullet proto.InternalMessageInfo

func (m *Game_C_ChangeBullet) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

//用户锁定
type Game_C_LockFish struct {
	FishID               int32    `protobuf:"varint,1,opt,name=FishID,proto3" json:"FishID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_LockFish) Reset()         { *m = Game_C_LockFish{} }
func (m *Game_C_LockFish) String() string { return proto.CompactTextString(m) }
func (*Game_C_LockFish) ProtoMessage()    {}
func (*Game_C_LockFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{7}
}

func (m *Game_C_LockFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_LockFish.Unmarshal(m, b)
}
func (m *Game_C_LockFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_LockFish.Marshal(b, m, deterministic)
}
func (m *Game_C_LockFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_LockFish.Merge(m, src)
}
func (m *Game_C_LockFish) XXX_Size() int {
	return xxx_messageInfo_Game_C_LockFish.Size(m)
}
func (m *Game_C_LockFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_LockFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_LockFish proto.InternalMessageInfo

func (m *Game_C_LockFish) GetFishID() int32 {
	if m != nil {
		return m.FishID
	}
	return 0
}

//user
type Game_S_User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	UserGold             float32  `protobuf:"fixed32,3,opt,name=UserGold,proto3" json:"UserGold,omitempty"`
	UserDiamond          float32  `protobuf:"fixed32,4,opt,name=UserDiamond,proto3" json:"UserDiamond,omitempty"`
	MemberOrder          int32    `protobuf:"varint,5,opt,name=MemberOrder,proto3" json:"MemberOrder,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,6,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl,omitempty"`
	FaceID               int32    `protobuf:"varint,7,opt,name=FaceID,proto3" json:"FaceID,omitempty"`
	RoleID               int32    `protobuf:"varint,8,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	SuitID               int32    `protobuf:"varint,9,opt,name=SuitID,proto3" json:"SuitID,omitempty"`
	PhotoFrameID         int32    `protobuf:"varint,10,opt,name=PhotoFrameID,proto3" json:"PhotoFrameID,omitempty"`
	TableID              int32    `protobuf:"varint,11,opt,name=TableID,proto3" json:"TableID,omitempty"`
	ChairID              int32    `protobuf:"varint,12,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_User) Reset()         { *m = Game_S_User{} }
func (m *Game_S_User) String() string { return proto.CompactTextString(m) }
func (*Game_S_User) ProtoMessage()    {}
func (*Game_S_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{8}
}

func (m *Game_S_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_User.Unmarshal(m, b)
}
func (m *Game_S_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_User.Marshal(b, m, deterministic)
}
func (m *Game_S_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_User.Merge(m, src)
}
func (m *Game_S_User) XXX_Size() int {
	return xxx_messageInfo_Game_S_User.Size(m)
}
func (m *Game_S_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_User.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_User proto.InternalMessageInfo

func (m *Game_S_User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_S_User) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *Game_S_User) GetUserGold() float32 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *Game_S_User) GetUserDiamond() float32 {
	if m != nil {
		return m.UserDiamond
	}
	return 0
}

func (m *Game_S_User) GetMemberOrder() int32 {
	if m != nil {
		return m.MemberOrder
	}
	return 0
}

func (m *Game_S_User) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *Game_S_User) GetFaceID() int32 {
	if m != nil {
		return m.FaceID
	}
	return 0
}

func (m *Game_S_User) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *Game_S_User) GetSuitID() int32 {
	if m != nil {
		return m.SuitID
	}
	return 0
}

func (m *Game_S_User) GetPhotoFrameID() int32 {
	if m != nil {
		return m.PhotoFrameID
	}
	return 0
}

func (m *Game_S_User) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_S_User) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//请求失败
type Game_S_ReqlyFail struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_ReqlyFail) Reset()         { *m = Game_S_ReqlyFail{} }
func (m *Game_S_ReqlyFail) String() string { return proto.CompactTextString(m) }
func (*Game_S_ReqlyFail) ProtoMessage()    {}
func (*Game_S_ReqlyFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{9}
}

func (m *Game_S_ReqlyFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_ReqlyFail.Unmarshal(m, b)
}
func (m *Game_S_ReqlyFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_ReqlyFail.Marshal(b, m, deterministic)
}
func (m *Game_S_ReqlyFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_ReqlyFail.Merge(m, src)
}
func (m *Game_S_ReqlyFail) XXX_Size() int {
	return xxx_messageInfo_Game_S_ReqlyFail.Size(m)
}
func (m *Game_S_ReqlyFail) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_ReqlyFail.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_ReqlyFail proto.InternalMessageInfo

func (m *Game_S_ReqlyFail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Game_S_ReqlyFail) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

//key []int32
type Int32Array struct {
	Data                 []int32  `protobuf:"varint,1,rep,packed,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Array) Reset()         { *m = Int32Array{} }
func (m *Int32Array) String() string { return proto.CompactTextString(m) }
func (*Int32Array) ProtoMessage()    {}
func (*Int32Array) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{10}
}

func (m *Int32Array) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Array.Unmarshal(m, b)
}
func (m *Int32Array) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Array.Marshal(b, m, deterministic)
}
func (m *Int32Array) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Array.Merge(m, src)
}
func (m *Int32Array) XXX_Size() int {
	return xxx_messageInfo_Int32Array.Size(m)
}
func (m *Int32Array) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Array.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Array proto.InternalMessageInfo

func (m *Int32Array) GetData() []int32 {
	if m != nil {
		return m.Data
	}
	return nil
}

//登陆成功
type Game_S_LoginSuccess struct {
	BulletList           []int32       `protobuf:"varint,1,rep,packed,name=BulletList,proto3" json:"BulletList,omitempty"`
	FishListMultiple     []*Int32Array `protobuf:"bytes,2,rep,name=FishListMultiple,proto3" json:"FishListMultiple,omitempty"`
	Status               int32         `protobuf:"varint,3,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Game_S_LoginSuccess) Reset()         { *m = Game_S_LoginSuccess{} }
func (m *Game_S_LoginSuccess) String() string { return proto.CompactTextString(m) }
func (*Game_S_LoginSuccess) ProtoMessage()    {}
func (*Game_S_LoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{11}
}

func (m *Game_S_LoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LoginSuccess.Unmarshal(m, b)
}
func (m *Game_S_LoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LoginSuccess.Marshal(b, m, deterministic)
}
func (m *Game_S_LoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LoginSuccess.Merge(m, src)
}
func (m *Game_S_LoginSuccess) XXX_Size() int {
	return xxx_messageInfo_Game_S_LoginSuccess.Size(m)
}
func (m *Game_S_LoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LoginSuccess proto.InternalMessageInfo

func (m *Game_S_LoginSuccess) GetBulletList() []int32 {
	if m != nil {
		return m.BulletList
	}
	return nil
}

func (m *Game_S_LoginSuccess) GetFishListMultiple() []*Int32Array {
	if m != nil {
		return m.FishListMultiple
	}
	return nil
}

func (m *Game_S_LoginSuccess) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//起立通知消息
type Game_S_StandUpNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StandUpNotify) Reset()         { *m = Game_S_StandUpNotify{} }
func (m *Game_S_StandUpNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_StandUpNotify) ProtoMessage()    {}
func (*Game_S_StandUpNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{12}
}

func (m *Game_S_StandUpNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StandUpNotify.Unmarshal(m, b)
}
func (m *Game_S_StandUpNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StandUpNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_StandUpNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StandUpNotify.Merge(m, src)
}
func (m *Game_S_StandUpNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_StandUpNotify.Size(m)
}
func (m *Game_S_StandUpNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StandUpNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StandUpNotify proto.InternalMessageInfo

func (m *Game_S_StandUpNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//掉线通知消息
type Game_S_OffLineNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_OffLineNotify) Reset()         { *m = Game_S_OffLineNotify{} }
func (m *Game_S_OffLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OffLineNotify) ProtoMessage()    {}
func (*Game_S_OffLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{13}
}

func (m *Game_S_OffLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OffLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OffLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OffLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OffLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OffLineNotify.Merge(m, src)
}
func (m *Game_S_OffLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OffLineNotify.Size(m)
}
func (m *Game_S_OffLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OffLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OffLineNotify proto.InternalMessageInfo

func (m *Game_S_OffLineNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//上线通知消息
type Game_S_OnLineNotify struct {
	UserInfo             *Game_S_User `protobuf:"bytes,1,opt,name=UserInfo,proto3" json:"UserInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game_S_OnLineNotify) Reset()         { *m = Game_S_OnLineNotify{} }
func (m *Game_S_OnLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OnLineNotify) ProtoMessage()    {}
func (*Game_S_OnLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{14}
}

func (m *Game_S_OnLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OnLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OnLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OnLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OnLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OnLineNotify.Merge(m, src)
}
func (m *Game_S_OnLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OnLineNotify.Size(m)
}
func (m *Game_S_OnLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OnLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OnLineNotify proto.InternalMessageInfo

func (m *Game_S_OnLineNotify) GetUserInfo() *Game_S_User {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

//空闲场景消息
type Game_S_FreeScene struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_FreeScene) Reset()         { *m = Game_S_FreeScene{} }
func (m *Game_S_FreeScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_FreeScene) ProtoMessage()    {}
func (*Game_S_FreeScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{15}
}

func (m *Game_S_FreeScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_FreeScene.Unmarshal(m, b)
}
func (m *Game_S_FreeScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_FreeScene.Marshal(b, m, deterministic)
}
func (m *Game_S_FreeScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_FreeScene.Merge(m, src)
}
func (m *Game_S_FreeScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_FreeScene.Size(m)
}
func (m *Game_S_FreeScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_FreeScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_FreeScene proto.InternalMessageInfo

func (m *Game_S_FreeScene) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//鱼
type Fish struct {
	FishType             int32    `protobuf:"varint,1,opt,name=FishType,proto3" json:"FishType,omitempty"`
	PathID               int32    `protobuf:"varint,2,opt,name=PathID,proto3" json:"PathID,omitempty"`
	MakeTime             int32    `protobuf:"varint,3,opt,name=MakeTime,proto3" json:"MakeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Fish) Reset()         { *m = Fish{} }
func (m *Fish) String() string { return proto.CompactTextString(m) }
func (*Fish) ProtoMessage()    {}
func (*Fish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{16}
}

func (m *Fish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fish.Unmarshal(m, b)
}
func (m *Fish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fish.Marshal(b, m, deterministic)
}
func (m *Fish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fish.Merge(m, src)
}
func (m *Fish) XXX_Size() int {
	return xxx_messageInfo_Fish.Size(m)
}
func (m *Fish) XXX_DiscardUnknown() {
	xxx_messageInfo_Fish.DiscardUnknown(m)
}

var xxx_messageInfo_Fish proto.InternalMessageInfo

func (m *Fish) GetFishType() int32 {
	if m != nil {
		return m.FishType
	}
	return 0
}

func (m *Fish) GetPathID() int32 {
	if m != nil {
		return m.PathID
	}
	return 0
}

func (m *Fish) GetMakeTime() int32 {
	if m != nil {
		return m.MakeTime
	}
	return 0
}

//游戏场景消息
type Game_S_PlayScene struct {
	ChairID              int32                  `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BulletType           map[int32]int32        `protobuf:"bytes,3,rep,name=BulletType,proto3" json:"BulletType,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	FishPool             map[int32]*Fish        `protobuf:"bytes,4,rep,name=FishPool,proto3" json:"FishPool,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	LockFish             map[int32]int32        `protobuf:"bytes,5,rep,name=LockFish,proto3" json:"LockFish,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_PlayScene) Reset()         { *m = Game_S_PlayScene{} }
func (m *Game_S_PlayScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_PlayScene) ProtoMessage()    {}
func (*Game_S_PlayScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{17}
}

func (m *Game_S_PlayScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_PlayScene.Unmarshal(m, b)
}
func (m *Game_S_PlayScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_PlayScene.Marshal(b, m, deterministic)
}
func (m *Game_S_PlayScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_PlayScene.Merge(m, src)
}
func (m *Game_S_PlayScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_PlayScene.Size(m)
}
func (m *Game_S_PlayScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_PlayScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_PlayScene proto.InternalMessageInfo

func (m *Game_S_PlayScene) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_PlayScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_PlayScene) GetBulletType() map[int32]int32 {
	if m != nil {
		return m.BulletType
	}
	return nil
}

func (m *Game_S_PlayScene) GetFishPool() map[int32]*Fish {
	if m != nil {
		return m.FishPool
	}
	return nil
}

func (m *Game_S_PlayScene) GetLockFish() map[int32]int32 {
	if m != nil {
		return m.LockFish
	}
	return nil
}

//鱼群场景消息
type Game_S_GroupFishScene struct {
	ChairID              int32                  `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,2,rep,name=UserList,proto3" json:"UserList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BulletType           map[int32]int32        `protobuf:"bytes,3,rep,name=BulletType,proto3" json:"BulletType,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	GroupFish            *Game_S_GroupFish      `protobuf:"bytes,4,opt,name=GroupFish,proto3" json:"GroupFish,omitempty"`
	LockFish             map[int32]int32        `protobuf:"bytes,5,rep,name=LockFish,proto3" json:"LockFish,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_GroupFishScene) Reset()         { *m = Game_S_GroupFishScene{} }
func (m *Game_S_GroupFishScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_GroupFishScene) ProtoMessage()    {}
func (*Game_S_GroupFishScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{18}
}

func (m *Game_S_GroupFishScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GroupFishScene.Unmarshal(m, b)
}
func (m *Game_S_GroupFishScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GroupFishScene.Marshal(b, m, deterministic)
}
func (m *Game_S_GroupFishScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GroupFishScene.Merge(m, src)
}
func (m *Game_S_GroupFishScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_GroupFishScene.Size(m)
}
func (m *Game_S_GroupFishScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GroupFishScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GroupFishScene proto.InternalMessageInfo

func (m *Game_S_GroupFishScene) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_GroupFishScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_GroupFishScene) GetBulletType() map[int32]int32 {
	if m != nil {
		return m.BulletType
	}
	return nil
}

func (m *Game_S_GroupFishScene) GetGroupFish() *Game_S_GroupFish {
	if m != nil {
		return m.GroupFish
	}
	return nil
}

func (m *Game_S_GroupFishScene) GetLockFish() map[int32]int32 {
	if m != nil {
		return m.LockFish
	}
	return nil
}

//用户开炮
type Game_S_UserFire struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	BulletID             int32    `protobuf:"varint,2,opt,name=BulletID,proto3" json:"BulletID,omitempty"`
	BulletType           int32    `protobuf:"varint,3,opt,name=BulletType,proto3" json:"BulletType,omitempty"`
	BulletAngle          int32    `protobuf:"varint,4,opt,name=BulletAngle,proto3" json:"BulletAngle,omitempty"`
	UserMoney            float32  `protobuf:"fixed32,5,opt,name=UserMoney,proto3" json:"UserMoney,omitempty"`
	LockFish             int32    `protobuf:"varint,6,opt,name=LockFish,proto3" json:"LockFish,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserFire) Reset()         { *m = Game_S_UserFire{} }
func (m *Game_S_UserFire) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserFire) ProtoMessage()    {}
func (*Game_S_UserFire) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{19}
}

func (m *Game_S_UserFire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserFire.Unmarshal(m, b)
}
func (m *Game_S_UserFire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserFire.Marshal(b, m, deterministic)
}
func (m *Game_S_UserFire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserFire.Merge(m, src)
}
func (m *Game_S_UserFire) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserFire.Size(m)
}
func (m *Game_S_UserFire) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserFire.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserFire proto.InternalMessageInfo

func (m *Game_S_UserFire) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserFire) GetBulletID() int32 {
	if m != nil {
		return m.BulletID
	}
	return 0
}

func (m *Game_S_UserFire) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

func (m *Game_S_UserFire) GetBulletAngle() int32 {
	if m != nil {
		return m.BulletAngle
	}
	return 0
}

func (m *Game_S_UserFire) GetUserMoney() float32 {
	if m != nil {
		return m.UserMoney
	}
	return 0
}

func (m *Game_S_UserFire) GetLockFish() int32 {
	if m != nil {
		return m.LockFish
	}
	return 0
}

//捕获消息
type Game_S_CatchFish struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	FishID               int32    `protobuf:"varint,3,opt,name=FishID,proto3" json:"FishID,omitempty"`
	FishMultiple         int32    `protobuf:"varint,4,opt,name=FishMultiple,proto3" json:"FishMultiple,omitempty"`
	FishScore            float32  `protobuf:"fixed32,5,opt,name=FishScore,proto3" json:"FishScore,omitempty"`
	UserMoney            float32  `protobuf:"fixed32,6,opt,name=UserMoney,proto3" json:"UserMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_CatchFish) Reset()         { *m = Game_S_CatchFish{} }
func (m *Game_S_CatchFish) String() string { return proto.CompactTextString(m) }
func (*Game_S_CatchFish) ProtoMessage()    {}
func (*Game_S_CatchFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{20}
}

func (m *Game_S_CatchFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_CatchFish.Unmarshal(m, b)
}
func (m *Game_S_CatchFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_CatchFish.Marshal(b, m, deterministic)
}
func (m *Game_S_CatchFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_CatchFish.Merge(m, src)
}
func (m *Game_S_CatchFish) XXX_Size() int {
	return xxx_messageInfo_Game_S_CatchFish.Size(m)
}
func (m *Game_S_CatchFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_CatchFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_CatchFish proto.InternalMessageInfo

func (m *Game_S_CatchFish) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_CatchFish) GetFishID() int32 {
	if m != nil {
		return m.FishID
	}
	return 0
}

func (m *Game_S_CatchFish) GetFishMultiple() int32 {
	if m != nil {
		return m.FishMultiple
	}
	return 0
}

func (m *Game_S_CatchFish) GetFishScore() float32 {
	if m != nil {
		return m.FishScore
	}
	return 0
}

func (m *Game_S_CatchFish) GetUserMoney() float32 {
	if m != nil {
		return m.UserMoney
	}
	return 0
}

//用户变炮
type Game_S_ChangeBullet struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	BulletType           int32    `protobuf:"varint,2,opt,name=BulletType,proto3" json:"BulletType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_ChangeBullet) Reset()         { *m = Game_S_ChangeBullet{} }
func (m *Game_S_ChangeBullet) String() string { return proto.CompactTextString(m) }
func (*Game_S_ChangeBullet) ProtoMessage()    {}
func (*Game_S_ChangeBullet) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{21}
}

func (m *Game_S_ChangeBullet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_ChangeBullet.Unmarshal(m, b)
}
func (m *Game_S_ChangeBullet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_ChangeBullet.Marshal(b, m, deterministic)
}
func (m *Game_S_ChangeBullet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_ChangeBullet.Merge(m, src)
}
func (m *Game_S_ChangeBullet) XXX_Size() int {
	return xxx_messageInfo_Game_S_ChangeBullet.Size(m)
}
func (m *Game_S_ChangeBullet) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_ChangeBullet.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_ChangeBullet proto.InternalMessageInfo

func (m *Game_S_ChangeBullet) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_ChangeBullet) GetBulletType() int32 {
	if m != nil {
		return m.BulletType
	}
	return 0
}

//用户锁定
type Game_S_LockFish struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	FishID               int32    `protobuf:"varint,2,opt,name=FishID,proto3" json:"FishID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LockFish) Reset()         { *m = Game_S_LockFish{} }
func (m *Game_S_LockFish) String() string { return proto.CompactTextString(m) }
func (*Game_S_LockFish) ProtoMessage()    {}
func (*Game_S_LockFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{22}
}

func (m *Game_S_LockFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LockFish.Unmarshal(m, b)
}
func (m *Game_S_LockFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LockFish.Marshal(b, m, deterministic)
}
func (m *Game_S_LockFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LockFish.Merge(m, src)
}
func (m *Game_S_LockFish) XXX_Size() int {
	return xxx_messageInfo_Game_S_LockFish.Size(m)
}
func (m *Game_S_LockFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LockFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LockFish proto.InternalMessageInfo

func (m *Game_S_LockFish) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_LockFish) GetFishID() int32 {
	if m != nil {
		return m.FishID
	}
	return 0
}

//生成鱼消息
type Game_S_MakeFish struct {
	FishID               int32    `protobuf:"varint,1,opt,name=FishID,proto3" json:"FishID,omitempty"`
	FishType             int32    `protobuf:"varint,2,opt,name=FishType,proto3" json:"FishType,omitempty"`
	PathID               int32    `protobuf:"varint,3,opt,name=PathID,proto3" json:"PathID,omitempty"`
	MakeTime             int32    `protobuf:"varint,4,opt,name=MakeTime,proto3" json:"MakeTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_MakeFish) Reset()         { *m = Game_S_MakeFish{} }
func (m *Game_S_MakeFish) String() string { return proto.CompactTextString(m) }
func (*Game_S_MakeFish) ProtoMessage()    {}
func (*Game_S_MakeFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{23}
}

func (m *Game_S_MakeFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_MakeFish.Unmarshal(m, b)
}
func (m *Game_S_MakeFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_MakeFish.Marshal(b, m, deterministic)
}
func (m *Game_S_MakeFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_MakeFish.Merge(m, src)
}
func (m *Game_S_MakeFish) XXX_Size() int {
	return xxx_messageInfo_Game_S_MakeFish.Size(m)
}
func (m *Game_S_MakeFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_MakeFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_MakeFish proto.InternalMessageInfo

func (m *Game_S_MakeFish) GetFishID() int32 {
	if m != nil {
		return m.FishID
	}
	return 0
}

func (m *Game_S_MakeFish) GetFishType() int32 {
	if m != nil {
		return m.FishType
	}
	return 0
}

func (m *Game_S_MakeFish) GetPathID() int32 {
	if m != nil {
		return m.PathID
	}
	return 0
}

func (m *Game_S_MakeFish) GetMakeTime() int32 {
	if m != nil {
		return m.MakeTime
	}
	return 0
}

// 生成鱼消息列表
type Game_S_FishList struct {
	FishList             []*Game_S_MakeFish `protobuf:"bytes,1,rep,name=FishList,proto3" json:"FishList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Game_S_FishList) Reset()         { *m = Game_S_FishList{} }
func (m *Game_S_FishList) String() string { return proto.CompactTextString(m) }
func (*Game_S_FishList) ProtoMessage()    {}
func (*Game_S_FishList) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{24}
}

func (m *Game_S_FishList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_FishList.Unmarshal(m, b)
}
func (m *Game_S_FishList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_FishList.Marshal(b, m, deterministic)
}
func (m *Game_S_FishList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_FishList.Merge(m, src)
}
func (m *Game_S_FishList) XXX_Size() int {
	return xxx_messageInfo_Game_S_FishList.Size(m)
}
func (m *Game_S_FishList) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_FishList.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_FishList proto.InternalMessageInfo

func (m *Game_S_FishList) GetFishList() []*Game_S_MakeFish {
	if m != nil {
		return m.FishList
	}
	return nil
}

//鱼群消息
type Game_S_GroupFish struct {
	GroupFishID          int32              `protobuf:"varint,1,opt,name=GroupFishID,proto3" json:"GroupFishID,omitempty"`
	DurationTime         int64              `protobuf:"varint,2,opt,name=DurationTime,proto3" json:"DurationTime,omitempty"`
	FishList             []*Game_S_MakeFish `protobuf:"bytes,3,rep,name=FishList,proto3" json:"FishList,omitempty"`
	StartFishID          int32              `protobuf:"varint,4,opt,name=StartFishID,proto3" json:"StartFishID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Game_S_GroupFish) Reset()         { *m = Game_S_GroupFish{} }
func (m *Game_S_GroupFish) String() string { return proto.CompactTextString(m) }
func (*Game_S_GroupFish) ProtoMessage()    {}
func (*Game_S_GroupFish) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{25}
}

func (m *Game_S_GroupFish) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GroupFish.Unmarshal(m, b)
}
func (m *Game_S_GroupFish) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GroupFish.Marshal(b, m, deterministic)
}
func (m *Game_S_GroupFish) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GroupFish.Merge(m, src)
}
func (m *Game_S_GroupFish) XXX_Size() int {
	return xxx_messageInfo_Game_S_GroupFish.Size(m)
}
func (m *Game_S_GroupFish) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GroupFish.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GroupFish proto.InternalMessageInfo

func (m *Game_S_GroupFish) GetGroupFishID() int32 {
	if m != nil {
		return m.GroupFishID
	}
	return 0
}

func (m *Game_S_GroupFish) GetDurationTime() int64 {
	if m != nil {
		return m.DurationTime
	}
	return 0
}

func (m *Game_S_GroupFish) GetFishList() []*Game_S_MakeFish {
	if m != nil {
		return m.FishList
	}
	return nil
}

func (m *Game_S_GroupFish) GetStartFishID() int32 {
	if m != nil {
		return m.StartFishID
	}
	return 0
}

func init() {
	proto.RegisterType((*Game_C_TokenLogin)(nil), "msg.Game_C_TokenLogin")
	proto.RegisterType((*Game_C_RobotLogin)(nil), "msg.Game_C_RobotLogin")
	proto.RegisterType((*Game_C_UserSitDown)(nil), "msg.Game_C_UserSitDown")
	proto.RegisterType((*Game_C_UserStandUp)(nil), "msg.Game_C_UserStandUp")
	proto.RegisterType((*Game_C_UserFire)(nil), "msg.Game_C_UserFire")
	proto.RegisterType((*Game_C_CatchFish)(nil), "msg.Game_C_CatchFish")
	proto.RegisterType((*Game_C_ChangeBullet)(nil), "msg.Game_C_ChangeBullet")
	proto.RegisterType((*Game_C_LockFish)(nil), "msg.Game_C_LockFish")
	proto.RegisterType((*Game_S_User)(nil), "msg.Game_S_User")
	proto.RegisterType((*Game_S_ReqlyFail)(nil), "msg.Game_S_ReqlyFail")
	proto.RegisterType((*Int32Array)(nil), "msg.Int32Array")
	proto.RegisterType((*Game_S_LoginSuccess)(nil), "msg.Game_S_LoginSuccess")
	proto.RegisterType((*Game_S_StandUpNotify)(nil), "msg.Game_S_StandUpNotify")
	proto.RegisterType((*Game_S_OffLineNotify)(nil), "msg.Game_S_OffLineNotify")
	proto.RegisterType((*Game_S_OnLineNotify)(nil), "msg.Game_S_OnLineNotify")
	proto.RegisterType((*Game_S_FreeScene)(nil), "msg.Game_S_FreeScene")
	proto.RegisterType((*Fish)(nil), "msg.Fish")
	proto.RegisterType((*Game_S_PlayScene)(nil), "msg.Game_S_PlayScene")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_PlayScene.BulletTypeEntry")
	proto.RegisterMapType((map[int32]*Fish)(nil), "msg.Game_S_PlayScene.FishPoolEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_PlayScene.LockFishEntry")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_PlayScene.UserListEntry")
	proto.RegisterType((*Game_S_GroupFishScene)(nil), "msg.Game_S_GroupFishScene")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_GroupFishScene.BulletTypeEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_GroupFishScene.LockFishEntry")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_GroupFishScene.UserListEntry")
	proto.RegisterType((*Game_S_UserFire)(nil), "msg.Game_S_UserFire")
	proto.RegisterType((*Game_S_CatchFish)(nil), "msg.Game_S_CatchFish")
	proto.RegisterType((*Game_S_ChangeBullet)(nil), "msg.Game_S_ChangeBullet")
	proto.RegisterType((*Game_S_LockFish)(nil), "msg.Game_S_LockFish")
	proto.RegisterType((*Game_S_MakeFish)(nil), "msg.Game_S_MakeFish")
	proto.RegisterType((*Game_S_FishList)(nil), "msg.Game_S_FishList")
	proto.RegisterType((*Game_S_GroupFish)(nil), "msg.Game_S_GroupFish")
}

func init() { proto.RegisterFile("msg/cmd.proto", fileDescriptor_a090769f8e2c12a2) }

var fileDescriptor_a090769f8e2c12a2 = []byte{
	// 1082 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x57, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x97, 0xe3, 0xa4, 0xd7, 0x6e, 0xae, 0x6a, 0x31, 0x39, 0x64, 0x55, 0xe8, 0x88, 0x8c, 0x40,
	0x01, 0x9d, 0xca, 0x29, 0x15, 0x12, 0xe2, 0x84, 0x4e, 0x77, 0x49, 0xd3, 0x0b, 0x4a, 0xda, 0xca,
	0x6e, 0x79, 0xad, 0xb6, 0xc9, 0x36, 0xb1, 0x62, 0x7b, 0xc3, 0x7a, 0x03, 0xca, 0x47, 0x80, 0xcf,
	0xc1, 0x23, 0xdf, 0x82, 0x27, 0x3e, 0x14, 0x12, 0x9a, 0xdd, 0xf5, 0x7a, 0x37, 0xcd, 0x9f, 0x43,
	0x3c, 0xdd, 0x53, 0xfc, 0x1b, 0xcf, 0xfe, 0x66, 0x7e, 0x3b, 0xb3, 0xde, 0x09, 0x3a, 0x4c, 0xf3,
	0xc9, 0x37, 0xa3, 0x74, 0x7c, 0x3a, 0x67, 0x94, 0x53, 0xcf, 0x4d, 0xf3, 0x49, 0x70, 0x81, 0x3e,
	0xba, 0xc0, 0x29, 0xb9, 0xeb, 0xdc, 0xdd, 0xd0, 0x19, 0xc9, 0x06, 0x74, 0x12, 0x67, 0x5e, 0x03,
	0xd5, 0x04, 0xf2, 0x9d, 0xa6, 0xd3, 0x3a, 0x08, 0x25, 0xf0, 0x3e, 0x45, 0x07, 0x43, 0x3c, 0x9a,
	0xc6, 0x19, 0xe9, 0x77, 0xfd, 0x8a, 0x78, 0x53, 0x1a, 0x82, 0x73, 0x4d, 0x14, 0xd2, 0x7b, 0xca,
	0x25, 0xd1, 0x27, 0x68, 0xef, 0x36, 0x27, 0xac, 0xdf, 0x15, 0x4c, 0xb5, 0x50, 0x21, 0xcf, 0x47,
	0x4f, 0xde, 0x62, 0x3e, 0x9a, 0x2a, 0xa2, 0x5a, 0x58, 0xc0, 0xe0, 0x1d, 0xf2, 0x14, 0x0d, 0xb8,
	0x46, 0x31, 0xef, 0xd2, 0x5f, 0x33, 0xf0, 0xbf, 0xc1, 0xf7, 0x09, 0xd1, 0x44, 0x05, 0x84, 0x37,
	0x9d, 0x29, 0x8e, 0x59, 0xc9, 0xa4, 0x60, 0xd0, 0xb0, 0x99, 0x38, 0xce, 0xc6, 0xb7, 0xf3, 0x20,
	0x42, 0x47, 0x86, 0xb5, 0x17, 0x33, 0xe2, 0x3d, 0x47, 0xe8, 0xed, 0x22, 0x49, 0x08, 0xbf, 0x59,
	0xce, 0x89, 0xe2, 0x37, 0x2c, 0x5e, 0x13, 0xd5, 0x25, 0x7a, 0x93, 0x4d, 0x12, 0xa2, 0xc2, 0x98,
	0xa6, 0xa0, 0x87, 0x8e, 0x15, 0x69, 0x07, 0x64, 0xf4, 0xe2, 0x7c, 0xea, 0x9d, 0xa0, 0x7d, 0xe9,
	0xa2, 0x73, 0xd6, 0x18, 0xb6, 0x05, 0x7c, 0x74, 0xce, 0x0a, 0x05, 0xdf, 0xa2, 0x8f, 0x0b, 0x9e,
	0x29, 0xce, 0x26, 0x44, 0x2e, 0xd8, 0x95, 0x60, 0xf0, 0x95, 0xd6, 0x34, 0xa0, 0xa3, 0x99, 0x88,
	0x5e, 0x46, 0x70, 0xac, 0x08, 0xff, 0x54, 0x50, 0x5d, 0xf8, 0x46, 0x42, 0xff, 0xc6, 0x02, 0x9d,
	0xa0, 0xfd, 0xcb, 0x78, 0x46, 0x2e, 0x71, 0x4a, 0x54, 0xa9, 0x35, 0x86, 0x77, 0xe0, 0x75, 0x41,
	0x93, 0xb1, 0xef, 0x36, 0x9d, 0x56, 0x25, 0xd4, 0x18, 0xf6, 0x0a, 0x9e, 0xbb, 0x31, 0x4e, 0x69,
	0x36, 0xf6, 0xab, 0xe2, 0xb5, 0x69, 0x02, 0x8f, 0x21, 0x49, 0xef, 0x09, 0xbb, 0x62, 0x63, 0xc2,
	0xfc, 0x9a, 0xdc, 0x4d, 0xc3, 0xe4, 0x05, 0xe8, 0xe9, 0x3b, 0x82, 0xc7, 0xfd, 0x14, 0x4f, 0xc8,
	0x2d, 0x4b, 0xfc, 0x3d, 0x11, 0xdf, 0xb2, 0x09, 0x7d, 0x78, 0x04, 0xfd, 0xf0, 0x44, 0xe9, 0x13,
	0x08, 0xec, 0x21, 0x15, 0x7d, 0xb2, 0x2f, 0xed, 0x12, 0x81, 0x3d, 0x5a, 0xc4, 0x50, 0x8b, 0x03,
	0x69, 0x97, 0x08, 0x62, 0x5d, 0x4f, 0x29, 0xa7, 0x3d, 0x86, 0x53, 0x58, 0x85, 0xc4, 0x5b, 0xcb,
	0x66, 0x36, 0x5f, 0x7d, 0x63, 0xf3, 0x3d, 0xb5, 0x9a, 0x4f, 0xc4, 0xe3, 0x98, 0x2f, 0x72, 0xff,
	0x50, 0xc5, 0x13, 0x28, 0x18, 0xa8, 0x4e, 0x89, 0xee, 0x42, 0xf2, 0x73, 0xb2, 0xec, 0xe1, 0x38,
	0x81, 0x73, 0x75, 0xce, 0x18, 0x65, 0x1d, 0x3a, 0x2e, 0xaa, 0x5b, 0x1a, 0x60, 0xb7, 0x05, 0x18,
	0xe6, 0x93, 0xa2, 0x12, 0x05, 0x0e, 0x9a, 0x08, 0xf5, 0x33, 0x7e, 0xd6, 0x7e, 0xc3, 0x18, 0x5e,
	0x7a, 0x1e, 0xaa, 0x76, 0x31, 0xc7, 0xbe, 0xd3, 0x74, 0x5b, 0xb5, 0x50, 0x3c, 0x07, 0xbf, 0x3b,
	0xaa, 0xa5, 0xa2, 0x3b, 0x71, 0x22, 0xa3, 0xc5, 0x68, 0x44, 0xf2, 0xbc, 0x6c, 0xa9, 0x41, 0x9c,
	0x73, 0xb5, 0xc2, 0xb0, 0x78, 0xaf, 0xd0, 0x31, 0x74, 0x0c, 0x3c, 0x0f, 0x17, 0x09, 0x8f, 0xe7,
	0xa2, 0xf1, 0xdd, 0x56, 0xbd, 0x7d, 0x74, 0x9a, 0xe6, 0x93, 0xd3, 0x32, 0x6c, 0xf8, 0xc8, 0xd1,
	0x10, 0xef, 0x5a, 0xe2, 0x5f, 0xa2, 0x86, 0xca, 0x45, 0x9d, 0xc6, 0x4b, 0xca, 0xe3, 0x87, 0xa5,
	0xb9, 0x8d, 0x8e, 0x7d, 0x86, 0xcb, 0x15, 0x57, 0x0f, 0x0f, 0x83, 0x38, 0x23, 0x3b, 0x57, 0x74,
	0xb4, 0xde, 0xab, 0xcc, 0x58, 0xf0, 0x42, 0xf6, 0x6c, 0x3f, 0x7b, 0xa0, 0x62, 0x45, 0xbd, 0x7d,
	0x2c, 0x74, 0x18, 0x67, 0x21, 0xd4, 0x1e, 0xc1, 0x0b, 0x5d, 0xa5, 0x1e, 0x23, 0x24, 0x1a, 0x91,
	0x8c, 0x6c, 0x09, 0xf9, 0x13, 0xaa, 0x16, 0x27, 0x1e, 0x7e, 0x8d, 0x43, 0xaa, 0x31, 0x6c, 0xc9,
	0x35, 0xe6, 0xc6, 0x89, 0x97, 0x08, 0xd6, 0x0c, 0xf1, 0x8c, 0xdc, 0xc4, 0x29, 0x51, 0x9b, 0xa5,
	0x71, 0xf0, 0x77, 0x55, 0xa7, 0x71, 0x9d, 0xe0, 0xe5, 0x8e, 0x34, 0xbc, 0xd7, 0x52, 0xa2, 0x28,
	0xa8, 0x2c, 0xd5, 0xe7, 0xa6, 0x44, 0x4d, 0x71, 0x5a, 0x78, 0x9d, 0x67, 0x9c, 0x2d, 0x43, 0xbd,
	0xc8, 0x3b, 0xb7, 0x3e, 0x33, 0xae, 0xa0, 0xf8, 0x62, 0x3d, 0x45, 0xe9, 0x27, 0x49, 0xcc, 0xcf,
	0xe5, 0x6b, 0xb9, 0x0d, 0xd7, 0x94, 0x26, 0x7e, 0x75, 0x5b, 0x1e, 0x85, 0x97, 0xca, 0xa3, 0x80,
	0x40, 0x50, 0x7c, 0xc7, 0xfc, 0xda, 0x36, 0x82, 0xc2, 0x4b, 0x11, 0x14, 0xf0, 0x64, 0x88, 0x0e,
	0x2d, 0x8d, 0xde, 0x31, 0x72, 0x67, 0x64, 0xa9, 0x36, 0x0c, 0x1e, 0xbd, 0x2f, 0x51, 0xed, 0x17,
	0x9c, 0x2c, 0xe4, 0xc7, 0x6d, 0x5d, 0x33, 0xc8, 0xd7, 0xdf, 0x57, 0xbe, 0x73, 0x4e, 0x7e, 0x40,
	0x47, 0x2b, 0x7a, 0xd7, 0x10, 0x36, 0x4c, 0xc2, 0x9a, 0xb9, 0xbc, 0x87, 0x0e, 0x2d, 0xa5, 0x6b,
	0x16, 0x7f, 0x66, 0x67, 0x73, 0x20, 0xb2, 0x81, 0x45, 0x26, 0xcf, 0x2b, 0x74, 0x68, 0x09, 0xfe,
	0x2f, 0x49, 0x04, 0xbf, 0x55, 0xd1, 0x33, 0x25, 0xef, 0x82, 0xd1, 0xc5, 0x1c, 0x58, 0x76, 0x35,
	0x54, 0xf7, 0x51, 0x43, 0xb5, 0xcc, 0x6d, 0xb2, 0x79, 0x36, 0x76, 0xd5, 0x8f, 0x6b, 0xba, 0xea,
	0xeb, 0x2d, 0x3c, 0xdb, 0x5a, 0xeb, 0x0c, 0x1d, 0x68, 0x6f, 0x71, 0xb7, 0xd4, 0xdb, 0xcf, 0xd6,
	0x52, 0x85, 0xa5, 0x1f, 0xc8, 0x58, 0x69, 0xa7, 0x6d, 0x32, 0x3e, 0x8c, 0x9e, 0xfa, 0x5f, 0xbd,
	0xf0, 0x97, 0xa3, 0xe6, 0x85, 0xa8, 0x9c, 0x81, 0x36, 0x77, 0x81, 0x39, 0xc7, 0x54, 0x56, 0xe6,
	0x98, 0xe7, 0x2b, 0xb5, 0xdd, 0x31, 0x39, 0x55, 0x1f, 0x4d, 0x4e, 0x70, 0xf7, 0x41, 0x0e, 0x43,
	0x9a, 0x91, 0xa5, 0x98, 0x05, 0x2a, 0x61, 0x69, 0x80, 0xd8, 0xba, 0x74, 0x7b, 0x32, 0x76, 0x81,
	0x83, 0x3f, 0x1c, 0xfd, 0x75, 0x2c, 0x87, 0xae, 0xcd, 0x32, 0xca, 0x81, 0xc8, 0x35, 0x07, 0x22,
	0x18, 0x00, 0xe0, 0x49, 0x5f, 0x72, 0x32, 0x47, 0xcb, 0x06, 0x49, 0xca, 0x06, 0xa1, 0x8c, 0x14,
	0x49, 0x6a, 0x83, 0x2d, 0x61, 0x6f, 0x45, 0x42, 0x70, 0xa5, 0xef, 0x23, 0x6b, 0xa4, 0xdb, 0x9c,
	0xa8, 0xbd, 0xa7, 0x95, 0x47, 0xc3, 0x5e, 0x47, 0x17, 0x4f, 0x0f, 0x7b, 0xef, 0xa3, 0xda, 0x1e,
	0x34, 0x97, 0x9a, 0x04, 0x6e, 0x9b, 0x6d, 0x13, 0xa3, 0x75, 0xab, 0x55, 0x36, 0xde, 0x6a, 0xee,
	0xc6, 0x5b, 0xad, 0xba, 0x72, 0xab, 0x95, 0xf9, 0x17, 0x73, 0x83, 0xf7, 0x52, 0x86, 0xd0, 0xa3,
	0x48, 0xbd, 0xdd, 0x30, 0xcf, 0x4e, 0x91, 0x62, 0xa8, 0xbd, 0x82, 0x3f, 0xcb, 0xe2, 0x97, 0x07,
	0xbd, 0x89, 0xea, 0x1a, 0x68, 0x19, 0xa6, 0x09, 0x8a, 0xdd, 0x5d, 0x30, 0xcc, 0x63, 0x9a, 0x89,
	0xdc, 0x40, 0x8f, 0x1b, 0x5a, 0x36, 0x2b, 0x19, 0xf7, 0x7d, 0x92, 0x81, 0xb8, 0x11, 0xc7, 0x8c,
	0xab, 0xb8, 0xaa, 0xcb, 0x0d, 0xd3, 0xfd, 0x9e, 0xf8, 0xc3, 0x75, 0xf6, 0x6f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x51, 0x34, 0x18, 0x65, 0x81, 0x0d, 0x00, 0x00,
}
