// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/cmd.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登陆消息
type Game_C_TokenLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	MachineID            string   `protobuf:"bytes,2,opt,name=MachineID,proto3" json:"MachineID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_TokenLogin) Reset()         { *m = Game_C_TokenLogin{} }
func (m *Game_C_TokenLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_TokenLogin) ProtoMessage()    {}
func (*Game_C_TokenLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{0}
}

func (m *Game_C_TokenLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_TokenLogin.Unmarshal(m, b)
}
func (m *Game_C_TokenLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_TokenLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_TokenLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_TokenLogin.Merge(m, src)
}
func (m *Game_C_TokenLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_TokenLogin.Size(m)
}
func (m *Game_C_TokenLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_TokenLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_TokenLogin proto.InternalMessageInfo

func (m *Game_C_TokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Game_C_TokenLogin) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

//机器人登陆
type Game_C_RobotLogin struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	BatchID              int32    `protobuf:"varint,2,opt,name=BatchID,proto3" json:"BatchID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_RobotLogin) Reset()         { *m = Game_C_RobotLogin{} }
func (m *Game_C_RobotLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_RobotLogin) ProtoMessage()    {}
func (*Game_C_RobotLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{1}
}

func (m *Game_C_RobotLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_RobotLogin.Unmarshal(m, b)
}
func (m *Game_C_RobotLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_RobotLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_RobotLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_RobotLogin.Merge(m, src)
}
func (m *Game_C_RobotLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_RobotLogin.Size(m)
}
func (m *Game_C_RobotLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_RobotLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_RobotLogin proto.InternalMessageInfo

func (m *Game_C_RobotLogin) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_C_RobotLogin) GetBatchID() int32 {
	if m != nil {
		return m.BatchID
	}
	return 0
}

//用户坐下
type Game_C_UserSitDown struct {
	TableID              int32    `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID,omitempty"`
	ChairID              int32    `protobuf:"varint,2,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserSitDown) Reset()         { *m = Game_C_UserSitDown{} }
func (m *Game_C_UserSitDown) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserSitDown) ProtoMessage()    {}
func (*Game_C_UserSitDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{2}
}

func (m *Game_C_UserSitDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserSitDown.Unmarshal(m, b)
}
func (m *Game_C_UserSitDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserSitDown.Marshal(b, m, deterministic)
}
func (m *Game_C_UserSitDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserSitDown.Merge(m, src)
}
func (m *Game_C_UserSitDown) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserSitDown.Size(m)
}
func (m *Game_C_UserSitDown) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserSitDown.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserSitDown proto.InternalMessageInfo

func (m *Game_C_UserSitDown) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_C_UserSitDown) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//用户起立
type Game_C_UserStandUp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserStandUp) Reset()         { *m = Game_C_UserStandUp{} }
func (m *Game_C_UserStandUp) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserStandUp) ProtoMessage()    {}
func (*Game_C_UserStandUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{3}
}

func (m *Game_C_UserStandUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserStandUp.Unmarshal(m, b)
}
func (m *Game_C_UserStandUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserStandUp.Marshal(b, m, deterministic)
}
func (m *Game_C_UserStandUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserStandUp.Merge(m, src)
}
func (m *Game_C_UserStandUp) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserStandUp.Size(m)
}
func (m *Game_C_UserStandUp) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserStandUp.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserStandUp proto.InternalMessageInfo

//用户比牌
type Game_C_UserBP struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserBP) Reset()         { *m = Game_C_UserBP{} }
func (m *Game_C_UserBP) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserBP) ProtoMessage()    {}
func (*Game_C_UserBP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{4}
}

func (m *Game_C_UserBP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserBP.Unmarshal(m, b)
}
func (m *Game_C_UserBP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserBP.Marshal(b, m, deterministic)
}
func (m *Game_C_UserBP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserBP.Merge(m, src)
}
func (m *Game_C_UserBP) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserBP.Size(m)
}
func (m *Game_C_UserBP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserBP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserBP proto.InternalMessageInfo

func (m *Game_C_UserBP) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//用户看牌
type Game_C_UserKP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserKP) Reset()         { *m = Game_C_UserKP{} }
func (m *Game_C_UserKP) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserKP) ProtoMessage()    {}
func (*Game_C_UserKP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{5}
}

func (m *Game_C_UserKP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserKP.Unmarshal(m, b)
}
func (m *Game_C_UserKP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserKP.Marshal(b, m, deterministic)
}
func (m *Game_C_UserKP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserKP.Merge(m, src)
}
func (m *Game_C_UserKP) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserKP.Size(m)
}
func (m *Game_C_UserKP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserKP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserKP proto.InternalMessageInfo

//用户弃牌
type Game_C_UserQP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserQP) Reset()         { *m = Game_C_UserQP{} }
func (m *Game_C_UserQP) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserQP) ProtoMessage()    {}
func (*Game_C_UserQP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{6}
}

func (m *Game_C_UserQP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserQP.Unmarshal(m, b)
}
func (m *Game_C_UserQP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserQP.Marshal(b, m, deterministic)
}
func (m *Game_C_UserQP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserQP.Merge(m, src)
}
func (m *Game_C_UserQP) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserQP.Size(m)
}
func (m *Game_C_UserQP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserQP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserQP proto.InternalMessageInfo

//用户下注
type Game_C_UserJetton struct {
	Multiple             int32    `protobuf:"varint,1,opt,name=Multiple,proto3" json:"Multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserJetton) Reset()         { *m = Game_C_UserJetton{} }
func (m *Game_C_UserJetton) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserJetton) ProtoMessage()    {}
func (*Game_C_UserJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{7}
}

func (m *Game_C_UserJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserJetton.Unmarshal(m, b)
}
func (m *Game_C_UserJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserJetton.Marshal(b, m, deterministic)
}
func (m *Game_C_UserJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserJetton.Merge(m, src)
}
func (m *Game_C_UserJetton) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserJetton.Size(m)
}
func (m *Game_C_UserJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserJetton proto.InternalMessageInfo

func (m *Game_C_UserJetton) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//用户摊牌
type Game_C_UserTP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserTP) Reset()         { *m = Game_C_UserTP{} }
func (m *Game_C_UserTP) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserTP) ProtoMessage()    {}
func (*Game_C_UserTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{8}
}

func (m *Game_C_UserTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserTP.Unmarshal(m, b)
}
func (m *Game_C_UserTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserTP.Marshal(b, m, deterministic)
}
func (m *Game_C_UserTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserTP.Merge(m, src)
}
func (m *Game_C_UserTP) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserTP.Size(m)
}
func (m *Game_C_UserTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserTP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserTP proto.InternalMessageInfo

//请求失败
type Game_S_ReqlyFail struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode,omitempty"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_ReqlyFail) Reset()         { *m = Game_S_ReqlyFail{} }
func (m *Game_S_ReqlyFail) String() string { return proto.CompactTextString(m) }
func (*Game_S_ReqlyFail) ProtoMessage()    {}
func (*Game_S_ReqlyFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{9}
}

func (m *Game_S_ReqlyFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_ReqlyFail.Unmarshal(m, b)
}
func (m *Game_S_ReqlyFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_ReqlyFail.Marshal(b, m, deterministic)
}
func (m *Game_S_ReqlyFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_ReqlyFail.Merge(m, src)
}
func (m *Game_S_ReqlyFail) XXX_Size() int {
	return xxx_messageInfo_Game_S_ReqlyFail.Size(m)
}
func (m *Game_S_ReqlyFail) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_ReqlyFail.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_ReqlyFail proto.InternalMessageInfo

func (m *Game_S_ReqlyFail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Game_S_ReqlyFail) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

//登陆成功
type Game_S_LoginSuccess struct {
	GameJettonTime       int32    `protobuf:"varint,1,opt,name=GameJettonTime,proto3" json:"GameJettonTime,omitempty"`
	JettonList           []int32  `protobuf:"varint,2,rep,packed,name=JettonList,proto3" json:"JettonList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LoginSuccess) Reset()         { *m = Game_S_LoginSuccess{} }
func (m *Game_S_LoginSuccess) String() string { return proto.CompactTextString(m) }
func (*Game_S_LoginSuccess) ProtoMessage()    {}
func (*Game_S_LoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{10}
}

func (m *Game_S_LoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LoginSuccess.Unmarshal(m, b)
}
func (m *Game_S_LoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LoginSuccess.Marshal(b, m, deterministic)
}
func (m *Game_S_LoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LoginSuccess.Merge(m, src)
}
func (m *Game_S_LoginSuccess) XXX_Size() int {
	return xxx_messageInfo_Game_S_LoginSuccess.Size(m)
}
func (m *Game_S_LoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LoginSuccess proto.InternalMessageInfo

func (m *Game_S_LoginSuccess) GetGameJettonTime() int32 {
	if m != nil {
		return m.GameJettonTime
	}
	return 0
}

func (m *Game_S_LoginSuccess) GetJettonList() []int32 {
	if m != nil {
		return m.JettonList
	}
	return nil
}

//坐下通知消息
type Game_S_SitDownNotify struct {
	Data                 *Game_S_User `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game_S_SitDownNotify) Reset()         { *m = Game_S_SitDownNotify{} }
func (m *Game_S_SitDownNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_SitDownNotify) ProtoMessage()    {}
func (*Game_S_SitDownNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{11}
}

func (m *Game_S_SitDownNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_SitDownNotify.Unmarshal(m, b)
}
func (m *Game_S_SitDownNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_SitDownNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_SitDownNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_SitDownNotify.Merge(m, src)
}
func (m *Game_S_SitDownNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_SitDownNotify.Size(m)
}
func (m *Game_S_SitDownNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_SitDownNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_SitDownNotify proto.InternalMessageInfo

func (m *Game_S_SitDownNotify) GetData() *Game_S_User {
	if m != nil {
		return m.Data
	}
	return nil
}

//起立通知消息
type Game_S_StandUpNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StandUpNotify) Reset()         { *m = Game_S_StandUpNotify{} }
func (m *Game_S_StandUpNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_StandUpNotify) ProtoMessage()    {}
func (*Game_S_StandUpNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{12}
}

func (m *Game_S_StandUpNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StandUpNotify.Unmarshal(m, b)
}
func (m *Game_S_StandUpNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StandUpNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_StandUpNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StandUpNotify.Merge(m, src)
}
func (m *Game_S_StandUpNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_StandUpNotify.Size(m)
}
func (m *Game_S_StandUpNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StandUpNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StandUpNotify proto.InternalMessageInfo

func (m *Game_S_StandUpNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//掉线通知消息
type Game_S_OffLineNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_OffLineNotify) Reset()         { *m = Game_S_OffLineNotify{} }
func (m *Game_S_OffLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OffLineNotify) ProtoMessage()    {}
func (*Game_S_OffLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{13}
}

func (m *Game_S_OffLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OffLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OffLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OffLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OffLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OffLineNotify.Merge(m, src)
}
func (m *Game_S_OffLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OffLineNotify.Size(m)
}
func (m *Game_S_OffLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OffLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OffLineNotify proto.InternalMessageInfo

func (m *Game_S_OffLineNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//上线通知消息
type Game_S_OnLineNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_OnLineNotify) Reset()         { *m = Game_S_OnLineNotify{} }
func (m *Game_S_OnLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OnLineNotify) ProtoMessage()    {}
func (*Game_S_OnLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{14}
}

func (m *Game_S_OnLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OnLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OnLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OnLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OnLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OnLineNotify.Merge(m, src)
}
func (m *Game_S_OnLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OnLineNotify.Size(m)
}
func (m *Game_S_OnLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OnLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OnLineNotify proto.InternalMessageInfo

func (m *Game_S_OnLineNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//user
type Game_S_User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=NikeName,proto3" json:"NikeName,omitempty"`
	UserGold             float32  `protobuf:"fixed32,3,opt,name=UserGold,proto3" json:"UserGold,omitempty"`
	UserDiamond          float32  `protobuf:"fixed32,4,opt,name=UserDiamond,proto3" json:"UserDiamond,omitempty"`
	MemberOrder          int32    `protobuf:"varint,5,opt,name=MemberOrder,proto3" json:"MemberOrder,omitempty"`
	HeadImageUrl         string   `protobuf:"bytes,6,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl,omitempty"`
	FaceID               int32    `protobuf:"varint,7,opt,name=FaceID,proto3" json:"FaceID,omitempty"`
	RoleID               int32    `protobuf:"varint,8,opt,name=RoleID,proto3" json:"RoleID,omitempty"`
	SuitID               int32    `protobuf:"varint,9,opt,name=SuitID,proto3" json:"SuitID,omitempty"`
	PhotoFrameID         int32    `protobuf:"varint,10,opt,name=PhotoFrameID,proto3" json:"PhotoFrameID,omitempty"`
	TableID              int32    `protobuf:"varint,11,opt,name=TableID,proto3" json:"TableID,omitempty"`
	ChairID              int32    `protobuf:"varint,12,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_User) Reset()         { *m = Game_S_User{} }
func (m *Game_S_User) String() string { return proto.CompactTextString(m) }
func (*Game_S_User) ProtoMessage()    {}
func (*Game_S_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{15}
}

func (m *Game_S_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_User.Unmarshal(m, b)
}
func (m *Game_S_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_User.Marshal(b, m, deterministic)
}
func (m *Game_S_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_User.Merge(m, src)
}
func (m *Game_S_User) XXX_Size() int {
	return xxx_messageInfo_Game_S_User.Size(m)
}
func (m *Game_S_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_User.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_User proto.InternalMessageInfo

func (m *Game_S_User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_S_User) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *Game_S_User) GetUserGold() float32 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *Game_S_User) GetUserDiamond() float32 {
	if m != nil {
		return m.UserDiamond
	}
	return 0
}

func (m *Game_S_User) GetMemberOrder() int32 {
	if m != nil {
		return m.MemberOrder
	}
	return 0
}

func (m *Game_S_User) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *Game_S_User) GetFaceID() int32 {
	if m != nil {
		return m.FaceID
	}
	return 0
}

func (m *Game_S_User) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *Game_S_User) GetSuitID() int32 {
	if m != nil {
		return m.SuitID
	}
	return 0
}

func (m *Game_S_User) GetPhotoFrameID() int32 {
	if m != nil {
		return m.PhotoFrameID
	}
	return 0
}

func (m *Game_S_User) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_S_User) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//空闲场景
type Game_S_FreeScene struct {
	SceneStartTime       int64                  `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime,omitempty"`
	UserChairID          int32                  `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID,omitempty"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_FreeScene) Reset()         { *m = Game_S_FreeScene{} }
func (m *Game_S_FreeScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_FreeScene) ProtoMessage()    {}
func (*Game_S_FreeScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{16}
}

func (m *Game_S_FreeScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_FreeScene.Unmarshal(m, b)
}
func (m *Game_S_FreeScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_FreeScene.Marshal(b, m, deterministic)
}
func (m *Game_S_FreeScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_FreeScene.Merge(m, src)
}
func (m *Game_S_FreeScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_FreeScene.Size(m)
}
func (m *Game_S_FreeScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_FreeScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_FreeScene proto.InternalMessageInfo

func (m *Game_S_FreeScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_FreeScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_FreeScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

//下注场景
type Game_S_JettonScene struct {
	SceneStartTime       int64                       `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime,omitempty"`
	UserChairID          int32                       `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID,omitempty"`
	UserList             map[int32]*Game_S_User      `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserListJetton       map[int32]*Game_List_Jetton `protobuf:"bytes,4,rep,name=UserListJetton,proto3" json:"UserListJetton,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurrentChairID       int32                       `protobuf:"varint,5,opt,name=CurrentChairID,proto3" json:"CurrentChairID,omitempty"`
	WinsChairID          int32                       `protobuf:"varint,6,opt,name=WinsChairID,proto3" json:"WinsChairID,omitempty"`
	Rounds               int32                       `protobuf:"varint,7,opt,name=Rounds,proto3" json:"Rounds,omitempty"`
	UserListKP           map[int32]bool              `protobuf:"bytes,8,rep,name=UserListKP,proto3" json:"UserListKP,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	UserListQP           map[int32]bool              `protobuf:"bytes,9,rep,name=UserListQP,proto3" json:"UserListQP,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *Game_S_JettonScene) Reset()         { *m = Game_S_JettonScene{} }
func (m *Game_S_JettonScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_JettonScene) ProtoMessage()    {}
func (*Game_S_JettonScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{17}
}

func (m *Game_S_JettonScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_JettonScene.Unmarshal(m, b)
}
func (m *Game_S_JettonScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_JettonScene.Marshal(b, m, deterministic)
}
func (m *Game_S_JettonScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_JettonScene.Merge(m, src)
}
func (m *Game_S_JettonScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_JettonScene.Size(m)
}
func (m *Game_S_JettonScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_JettonScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_JettonScene proto.InternalMessageInfo

func (m *Game_S_JettonScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_JettonScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_JettonScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_JettonScene) GetUserListJetton() map[int32]*Game_List_Jetton {
	if m != nil {
		return m.UserListJetton
	}
	return nil
}

func (m *Game_S_JettonScene) GetCurrentChairID() int32 {
	if m != nil {
		return m.CurrentChairID
	}
	return 0
}

func (m *Game_S_JettonScene) GetWinsChairID() int32 {
	if m != nil {
		return m.WinsChairID
	}
	return 0
}

func (m *Game_S_JettonScene) GetRounds() int32 {
	if m != nil {
		return m.Rounds
	}
	return 0
}

func (m *Game_S_JettonScene) GetUserListKP() map[int32]bool {
	if m != nil {
		return m.UserListKP
	}
	return nil
}

func (m *Game_S_JettonScene) GetUserListQP() map[int32]bool {
	if m != nil {
		return m.UserListQP
	}
	return nil
}

type Game_List_Jetton struct {
	UserListJetton       []int32  `protobuf:"varint,1,rep,packed,name=UserListJetton,proto3" json:"UserListJetton,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_List_Jetton) Reset()         { *m = Game_List_Jetton{} }
func (m *Game_List_Jetton) String() string { return proto.CompactTextString(m) }
func (*Game_List_Jetton) ProtoMessage()    {}
func (*Game_List_Jetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{18}
}

func (m *Game_List_Jetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_List_Jetton.Unmarshal(m, b)
}
func (m *Game_List_Jetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_List_Jetton.Marshal(b, m, deterministic)
}
func (m *Game_List_Jetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_List_Jetton.Merge(m, src)
}
func (m *Game_List_Jetton) XXX_Size() int {
	return xxx_messageInfo_Game_List_Jetton.Size(m)
}
func (m *Game_List_Jetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_List_Jetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_List_Jetton proto.InternalMessageInfo

func (m *Game_List_Jetton) GetUserListJetton() []int32 {
	if m != nil {
		return m.UserListJetton
	}
	return nil
}

//摊牌场景
type Game_S_TPScene struct {
	SceneStartTime       int64                          `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime,omitempty"`
	UserChairID          int32                          `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID,omitempty"`
	UserList             map[int32]*Game_S_User         `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserListTP           map[int32]*Game_S_LotteryPoker `protobuf:"bytes,4,rep,name=UserListTP,proto3" json:"UserListTP,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CurrentChairID       int32                          `protobuf:"varint,5,opt,name=CurrentChairID,proto3" json:"CurrentChairID,omitempty"`
	WinsChairID          int32                          `protobuf:"varint,6,opt,name=WinsChairID,proto3" json:"WinsChairID,omitempty"`
	Rounds               int32                          `protobuf:"varint,7,opt,name=Rounds,proto3" json:"Rounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Game_S_TPScene) Reset()         { *m = Game_S_TPScene{} }
func (m *Game_S_TPScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_TPScene) ProtoMessage()    {}
func (*Game_S_TPScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{19}
}

func (m *Game_S_TPScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_TPScene.Unmarshal(m, b)
}
func (m *Game_S_TPScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_TPScene.Marshal(b, m, deterministic)
}
func (m *Game_S_TPScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_TPScene.Merge(m, src)
}
func (m *Game_S_TPScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_TPScene.Size(m)
}
func (m *Game_S_TPScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_TPScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_TPScene proto.InternalMessageInfo

func (m *Game_S_TPScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_TPScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_TPScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_TPScene) GetUserListTP() map[int32]*Game_S_LotteryPoker {
	if m != nil {
		return m.UserListTP
	}
	return nil
}

func (m *Game_S_TPScene) GetCurrentChairID() int32 {
	if m != nil {
		return m.CurrentChairID
	}
	return 0
}

func (m *Game_S_TPScene) GetWinsChairID() int32 {
	if m != nil {
		return m.WinsChairID
	}
	return 0
}

func (m *Game_S_TPScene) GetRounds() int32 {
	if m != nil {
		return m.Rounds
	}
	return 0
}

type Game_S_LotteryPoker struct {
	PokerType            int32    `protobuf:"varint,1,opt,name=PokerType,proto3" json:"PokerType,omitempty"`
	LotteryPoker         []int32  `protobuf:"varint,2,rep,packed,name=LotteryPoker,proto3" json:"LotteryPoker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LotteryPoker) Reset()         { *m = Game_S_LotteryPoker{} }
func (m *Game_S_LotteryPoker) String() string { return proto.CompactTextString(m) }
func (*Game_S_LotteryPoker) ProtoMessage()    {}
func (*Game_S_LotteryPoker) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{20}
}

func (m *Game_S_LotteryPoker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LotteryPoker.Unmarshal(m, b)
}
func (m *Game_S_LotteryPoker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LotteryPoker.Marshal(b, m, deterministic)
}
func (m *Game_S_LotteryPoker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LotteryPoker.Merge(m, src)
}
func (m *Game_S_LotteryPoker) XXX_Size() int {
	return xxx_messageInfo_Game_S_LotteryPoker.Size(m)
}
func (m *Game_S_LotteryPoker) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LotteryPoker.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LotteryPoker proto.InternalMessageInfo

func (m *Game_S_LotteryPoker) GetPokerType() int32 {
	if m != nil {
		return m.PokerType
	}
	return 0
}

func (m *Game_S_LotteryPoker) GetLotteryPoker() []int32 {
	if m != nil {
		return m.LotteryPoker
	}
	return nil
}

//开始定时器
type Game_S_StartTime struct {
	CurrentChairID       int32    `protobuf:"varint,1,opt,name=CurrentChairID,proto3" json:"CurrentChairID,omitempty"`
	WinsChairID          int32    `protobuf:"varint,2,opt,name=WinsChairID,proto3" json:"WinsChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StartTime) Reset()         { *m = Game_S_StartTime{} }
func (m *Game_S_StartTime) String() string { return proto.CompactTextString(m) }
func (*Game_S_StartTime) ProtoMessage()    {}
func (*Game_S_StartTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{21}
}

func (m *Game_S_StartTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StartTime.Unmarshal(m, b)
}
func (m *Game_S_StartTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StartTime.Marshal(b, m, deterministic)
}
func (m *Game_S_StartTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StartTime.Merge(m, src)
}
func (m *Game_S_StartTime) XXX_Size() int {
	return xxx_messageInfo_Game_S_StartTime.Size(m)
}
func (m *Game_S_StartTime) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StartTime.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StartTime proto.InternalMessageInfo

func (m *Game_S_StartTime) GetCurrentChairID() int32 {
	if m != nil {
		return m.CurrentChairID
	}
	return 0
}

func (m *Game_S_StartTime) GetWinsChairID() int32 {
	if m != nil {
		return m.WinsChairID
	}
	return 0
}

type Game_S_StartJetton struct {
	CurrentChairID       int32    `protobuf:"varint,1,opt,name=CurrentChairID,proto3" json:"CurrentChairID,omitempty"`
	CurrentChip          int32    `protobuf:"varint,2,opt,name=CurrentChip,proto3" json:"CurrentChip,omitempty"`
	CurrentRounds        int32    `protobuf:"varint,3,opt,name=CurrentRounds,proto3" json:"CurrentRounds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StartJetton) Reset()         { *m = Game_S_StartJetton{} }
func (m *Game_S_StartJetton) String() string { return proto.CompactTextString(m) }
func (*Game_S_StartJetton) ProtoMessage()    {}
func (*Game_S_StartJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{22}
}

func (m *Game_S_StartJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StartJetton.Unmarshal(m, b)
}
func (m *Game_S_StartJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StartJetton.Marshal(b, m, deterministic)
}
func (m *Game_S_StartJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StartJetton.Merge(m, src)
}
func (m *Game_S_StartJetton) XXX_Size() int {
	return xxx_messageInfo_Game_S_StartJetton.Size(m)
}
func (m *Game_S_StartJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StartJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StartJetton proto.InternalMessageInfo

func (m *Game_S_StartJetton) GetCurrentChairID() int32 {
	if m != nil {
		return m.CurrentChairID
	}
	return 0
}

func (m *Game_S_StartJetton) GetCurrentChip() int32 {
	if m != nil {
		return m.CurrentChip
	}
	return 0
}

func (m *Game_S_StartJetton) GetCurrentRounds() int32 {
	if m != nil {
		return m.CurrentRounds
	}
	return 0
}

//结束游戏消息
type Game_S_GameConclude struct {
	WinChairID           int32    `protobuf:"varint,1,opt,name=WinChairID,proto3" json:"WinChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_GameConclude) Reset()         { *m = Game_S_GameConclude{} }
func (m *Game_S_GameConclude) String() string { return proto.CompactTextString(m) }
func (*Game_S_GameConclude) ProtoMessage()    {}
func (*Game_S_GameConclude) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{23}
}

func (m *Game_S_GameConclude) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GameConclude.Unmarshal(m, b)
}
func (m *Game_S_GameConclude) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GameConclude.Marshal(b, m, deterministic)
}
func (m *Game_S_GameConclude) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GameConclude.Merge(m, src)
}
func (m *Game_S_GameConclude) XXX_Size() int {
	return xxx_messageInfo_Game_S_GameConclude.Size(m)
}
func (m *Game_S_GameConclude) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GameConclude.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GameConclude proto.InternalMessageInfo

func (m *Game_S_GameConclude) GetWinChairID() int32 {
	if m != nil {
		return m.WinChairID
	}
	return 0
}

//看牌通知
type Game_S_UserKP struct {
	ChairID              int32                          `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	UserListPoker        map[int32]*Game_S_LotteryPoker `protobuf:"bytes,2,rep,name=UserListPoker,proto3" json:"UserListPoker,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Game_S_UserKP) Reset()         { *m = Game_S_UserKP{} }
func (m *Game_S_UserKP) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserKP) ProtoMessage()    {}
func (*Game_S_UserKP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{24}
}

func (m *Game_S_UserKP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserKP.Unmarshal(m, b)
}
func (m *Game_S_UserKP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserKP.Marshal(b, m, deterministic)
}
func (m *Game_S_UserKP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserKP.Merge(m, src)
}
func (m *Game_S_UserKP) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserKP.Size(m)
}
func (m *Game_S_UserKP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserKP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserKP proto.InternalMessageInfo

func (m *Game_S_UserKP) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserKP) GetUserListPoker() map[int32]*Game_S_LotteryPoker {
	if m != nil {
		return m.UserListPoker
	}
	return nil
}

//弃牌通知
type Game_S_UserQP struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserQP) Reset()         { *m = Game_S_UserQP{} }
func (m *Game_S_UserQP) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserQP) ProtoMessage()    {}
func (*Game_S_UserQP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{25}
}

func (m *Game_S_UserQP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserQP.Unmarshal(m, b)
}
func (m *Game_S_UserQP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserQP.Marshal(b, m, deterministic)
}
func (m *Game_S_UserQP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserQP.Merge(m, src)
}
func (m *Game_S_UserQP) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserQP.Size(m)
}
func (m *Game_S_UserQP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserQP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserQP proto.InternalMessageInfo

func (m *Game_S_UserQP) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//比牌通知
type Game_S_UserBP struct {
	WinChairID           int32    `protobuf:"varint,1,opt,name=WinChairID,proto3" json:"WinChairID,omitempty"`
	LoseChairID          int32    `protobuf:"varint,2,opt,name=LoseChairID,proto3" json:"LoseChairID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserBP) Reset()         { *m = Game_S_UserBP{} }
func (m *Game_S_UserBP) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserBP) ProtoMessage()    {}
func (*Game_S_UserBP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{26}
}

func (m *Game_S_UserBP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserBP.Unmarshal(m, b)
}
func (m *Game_S_UserBP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserBP.Marshal(b, m, deterministic)
}
func (m *Game_S_UserBP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserBP.Merge(m, src)
}
func (m *Game_S_UserBP) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserBP.Size(m)
}
func (m *Game_S_UserBP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserBP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserBP proto.InternalMessageInfo

func (m *Game_S_UserBP) GetWinChairID() int32 {
	if m != nil {
		return m.WinChairID
	}
	return 0
}

func (m *Game_S_UserBP) GetLoseChairID() int32 {
	if m != nil {
		return m.LoseChairID
	}
	return 0
}

//下注通知
type Game_S_UserJetton struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	Multiple             int32    `protobuf:"varint,2,opt,name=Multiple,proto3" json:"Multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserJetton) Reset()         { *m = Game_S_UserJetton{} }
func (m *Game_S_UserJetton) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserJetton) ProtoMessage()    {}
func (*Game_S_UserJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{27}
}

func (m *Game_S_UserJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserJetton.Unmarshal(m, b)
}
func (m *Game_S_UserJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserJetton.Marshal(b, m, deterministic)
}
func (m *Game_S_UserJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserJetton.Merge(m, src)
}
func (m *Game_S_UserJetton) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserJetton.Size(m)
}
func (m *Game_S_UserJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserJetton proto.InternalMessageInfo

func (m *Game_S_UserJetton) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserJetton) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//摊牌通知
type Game_S_UserTP struct {
	ChairID              int32                `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID,omitempty"`
	UserListPoker        *Game_S_LotteryPoker `protobuf:"bytes,2,opt,name=UserListPoker,proto3" json:"UserListPoker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Game_S_UserTP) Reset()         { *m = Game_S_UserTP{} }
func (m *Game_S_UserTP) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserTP) ProtoMessage()    {}
func (*Game_S_UserTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_a090769f8e2c12a2, []int{28}
}

func (m *Game_S_UserTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserTP.Unmarshal(m, b)
}
func (m *Game_S_UserTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserTP.Marshal(b, m, deterministic)
}
func (m *Game_S_UserTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserTP.Merge(m, src)
}
func (m *Game_S_UserTP) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserTP.Size(m)
}
func (m *Game_S_UserTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserTP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserTP proto.InternalMessageInfo

func (m *Game_S_UserTP) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserTP) GetUserListPoker() *Game_S_LotteryPoker {
	if m != nil {
		return m.UserListPoker
	}
	return nil
}

func init() {
	proto.RegisterType((*Game_C_TokenLogin)(nil), "msg.Game_C_TokenLogin")
	proto.RegisterType((*Game_C_RobotLogin)(nil), "msg.Game_C_RobotLogin")
	proto.RegisterType((*Game_C_UserSitDown)(nil), "msg.Game_C_UserSitDown")
	proto.RegisterType((*Game_C_UserStandUp)(nil), "msg.Game_C_UserStandUp")
	proto.RegisterType((*Game_C_UserBP)(nil), "msg.Game_C_UserBP")
	proto.RegisterType((*Game_C_UserKP)(nil), "msg.Game_C_UserKP")
	proto.RegisterType((*Game_C_UserQP)(nil), "msg.Game_C_UserQP")
	proto.RegisterType((*Game_C_UserJetton)(nil), "msg.Game_C_UserJetton")
	proto.RegisterType((*Game_C_UserTP)(nil), "msg.Game_C_UserTP")
	proto.RegisterType((*Game_S_ReqlyFail)(nil), "msg.Game_S_ReqlyFail")
	proto.RegisterType((*Game_S_LoginSuccess)(nil), "msg.Game_S_LoginSuccess")
	proto.RegisterType((*Game_S_SitDownNotify)(nil), "msg.Game_S_SitDownNotify")
	proto.RegisterType((*Game_S_StandUpNotify)(nil), "msg.Game_S_StandUpNotify")
	proto.RegisterType((*Game_S_OffLineNotify)(nil), "msg.Game_S_OffLineNotify")
	proto.RegisterType((*Game_S_OnLineNotify)(nil), "msg.Game_S_OnLineNotify")
	proto.RegisterType((*Game_S_User)(nil), "msg.Game_S_User")
	proto.RegisterType((*Game_S_FreeScene)(nil), "msg.Game_S_FreeScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_FreeScene.UserListEntry")
	proto.RegisterType((*Game_S_JettonScene)(nil), "msg.Game_S_JettonScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_JettonScene.UserListEntry")
	proto.RegisterMapType((map[int32]*Game_List_Jetton)(nil), "msg.Game_S_JettonScene.UserListJettonEntry")
	proto.RegisterMapType((map[int32]bool)(nil), "msg.Game_S_JettonScene.UserListKPEntry")
	proto.RegisterMapType((map[int32]bool)(nil), "msg.Game_S_JettonScene.UserListQPEntry")
	proto.RegisterType((*Game_List_Jetton)(nil), "msg.Game_List_Jetton")
	proto.RegisterType((*Game_S_TPScene)(nil), "msg.Game_S_TPScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_TPScene.UserListEntry")
	proto.RegisterMapType((map[int32]*Game_S_LotteryPoker)(nil), "msg.Game_S_TPScene.UserListTPEntry")
	proto.RegisterType((*Game_S_LotteryPoker)(nil), "msg.Game_S_LotteryPoker")
	proto.RegisterType((*Game_S_StartTime)(nil), "msg.Game_S_StartTime")
	proto.RegisterType((*Game_S_StartJetton)(nil), "msg.Game_S_StartJetton")
	proto.RegisterType((*Game_S_GameConclude)(nil), "msg.Game_S_GameConclude")
	proto.RegisterType((*Game_S_UserKP)(nil), "msg.Game_S_UserKP")
	proto.RegisterMapType((map[int32]*Game_S_LotteryPoker)(nil), "msg.Game_S_UserKP.UserListPokerEntry")
	proto.RegisterType((*Game_S_UserQP)(nil), "msg.Game_S_UserQP")
	proto.RegisterType((*Game_S_UserBP)(nil), "msg.Game_S_UserBP")
	proto.RegisterType((*Game_S_UserJetton)(nil), "msg.Game_S_UserJetton")
	proto.RegisterType((*Game_S_UserTP)(nil), "msg.Game_S_UserTP")
}

func init() { proto.RegisterFile("msg/cmd.proto", fileDescriptor_a090769f8e2c12a2) }

var fileDescriptor_a090769f8e2c12a2 = []byte{
	// 1060 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xdf, 0x6e, 0xe3, 0xc4,
	0x17, 0x96, 0x93, 0x26, 0x9b, 0x4e, 0x36, 0xbb, 0xfd, 0xcd, 0xf6, 0x87, 0xac, 0x08, 0xa1, 0x30,
	0xbb, 0x2c, 0x5d, 0xad, 0x94, 0xa2, 0x45, 0x48, 0x68, 0xc5, 0x82, 0x68, 0xd2, 0x76, 0x43, 0x93,
	0xd6, 0xb1, 0x5d, 0x15, 0x21, 0x50, 0xe4, 0x26, 0xd3, 0xd4, 0xaa, 0xed, 0x09, 0xf6, 0x04, 0x94,
	0x7b, 0x5e, 0x80, 0x57, 0xe3, 0x29, 0xb8, 0xe0, 0x15, 0x90, 0xd0, 0xfc, 0xb1, 0x3d, 0xe3, 0xd4,
	0x6d, 0x91, 0xc2, 0x95, 0x7d, 0xbe, 0x39, 0xe7, 0x9b, 0x33, 0x67, 0xbe, 0x63, 0xcf, 0x80, 0x56,
	0x98, 0xcc, 0xf7, 0xa7, 0xe1, 0xac, 0xbb, 0x88, 0x09, 0x25, 0xb0, 0x1a, 0x26, 0x73, 0x74, 0x0c,
	0xfe, 0x77, 0xec, 0x85, 0x78, 0xd2, 0x9b, 0xb8, 0xe4, 0x06, 0x47, 0x43, 0x32, 0xf7, 0x23, 0xb8,
	0x0b, 0x6a, 0xdc, 0x32, 0x8d, 0x8e, 0xb1, 0xb7, 0x6d, 0x0b, 0x03, 0x7e, 0x08, 0xb6, 0x47, 0xde,
	0xf4, 0xda, 0x8f, 0xf0, 0xa0, 0x6f, 0x56, 0xf8, 0x48, 0x0e, 0xa0, 0xc3, 0x8c, 0xc8, 0x26, 0x97,
	0x84, 0x0a, 0xa2, 0x0f, 0x40, 0xfd, 0x3c, 0xc1, 0xf1, 0xa0, 0xcf, 0x99, 0x6a, 0xb6, 0xb4, 0xa0,
	0x09, 0x1e, 0x1d, 0x78, 0x74, 0x7a, 0x2d, 0x89, 0x6a, 0x76, 0x6a, 0xa2, 0xf7, 0x00, 0x4a, 0x1a,
	0xe6, 0xea, 0xf8, 0xb4, 0x4f, 0x7e, 0x8d, 0x98, 0xbf, 0xeb, 0x5d, 0x06, 0x38, 0x23, 0x4a, 0x4d,
	0x36, 0xd2, 0xbb, 0xf6, 0xfc, 0x38, 0x67, 0x92, 0x26, 0xda, 0xd5, 0x99, 0xa8, 0x17, 0xcd, 0xce,
	0x17, 0xe8, 0x15, 0x68, 0x29, 0xe8, 0x81, 0xa5, 0x12, 0x18, 0x3a, 0xc1, 0x53, 0xcd, 0xf5, 0xc4,
	0x2a, 0x00, 0x63, 0x0b, 0xed, 0x67, 0x6b, 0x66, 0xc0, 0x77, 0x98, 0x52, 0x12, 0xc1, 0x36, 0x68,
	0x8c, 0x96, 0x01, 0xf5, 0x17, 0x01, 0x96, 0x8c, 0x99, 0x5d, 0x60, 0x70, 0x2d, 0x34, 0x04, 0x3b,
	0x1c, 0x70, 0x26, 0x36, 0xfe, 0x39, 0x58, 0x1d, 0x79, 0x7e, 0xc0, 0xea, 0x7c, 0x18, 0xc7, 0x24,
	0xee, 0x91, 0x59, 0xca, 0x90, 0x03, 0x8c, 0x9e, 0x1b, 0xa3, 0x64, 0x2e, 0x37, 0x21, 0xb3, 0xd1,
	0x4f, 0xe0, 0x99, 0x64, 0xe3, 0xe5, 0x77, 0x96, 0xd3, 0x29, 0x4e, 0x12, 0xf8, 0x12, 0x3c, 0x61,
	0xb0, 0xc8, 0xcf, 0xf5, 0xc3, 0x94, 0xb5, 0x80, 0xc2, 0x8f, 0x00, 0x10, 0xd6, 0xd0, 0x4f, 0xa8,
	0x59, 0xe9, 0x54, 0xf7, 0x6a, 0xb6, 0x82, 0xa0, 0xaf, 0xc0, 0xae, 0xa4, 0x97, 0xfb, 0x72, 0x4a,
	0xa8, 0x7f, 0xb5, 0x82, 0x2f, 0xc0, 0x56, 0xdf, 0xa3, 0x1e, 0x67, 0x6d, 0xbe, 0xd9, 0xe9, 0x86,
	0xc9, 0xbc, 0x2b, 0x1d, 0xd9, 0x32, 0x6d, 0x3e, 0x8a, 0x3e, 0xcb, 0xa3, 0xc5, 0x5e, 0xc8, 0xe8,
	0xf2, 0x0d, 0xc8, 0x23, 0xce, 0xae, 0xae, 0x86, 0x7e, 0x84, 0xef, 0x8d, 0xd8, 0xcf, 0x0a, 0x70,
	0x16, 0x3d, 0x28, 0xe0, 0xef, 0x0a, 0x68, 0x2a, 0xa9, 0x96, 0x0a, 0xb6, 0x0d, 0x1a, 0xa7, 0xfe,
	0x0d, 0x3e, 0xf5, 0x42, 0x9c, 0x56, 0x3d, 0xb5, 0xd9, 0x18, 0xf3, 0x3a, 0x26, 0xc1, 0xcc, 0xac,
	0x76, 0x8c, 0xbd, 0x8a, 0x9d, 0xd9, 0xb0, 0x03, 0x9a, 0xec, 0xbd, 0xef, 0x7b, 0x21, 0x89, 0x66,
	0xe6, 0x16, 0x1f, 0x56, 0x21, 0xe6, 0x31, 0xc2, 0xe1, 0x25, 0x8e, 0xcf, 0xe2, 0x19, 0x8e, 0xcd,
	0x1a, 0x9f, 0x56, 0x85, 0x20, 0x02, 0x8f, 0xdf, 0x63, 0x6f, 0x36, 0x08, 0xbd, 0x39, 0x3e, 0x8f,
	0x03, 0xb3, 0xce, 0xe7, 0xd7, 0x30, 0x96, 0xf7, 0x91, 0x37, 0x65, 0xfd, 0xf1, 0x48, 0xe4, 0x2d,
	0x2c, 0x86, 0xdb, 0x84, 0xf7, 0x4d, 0x43, 0xe0, 0xc2, 0x62, 0xb8, 0xb3, 0xf4, 0xe9, 0xa0, 0x6f,
	0x6e, 0x0b, 0x5c, 0x58, 0x6c, 0x2e, 0xeb, 0x9a, 0x50, 0x72, 0x14, 0x7b, 0x21, 0x8b, 0x02, 0x7c,
	0x54, 0xc3, 0xd4, 0x66, 0x6c, 0x96, 0x36, 0xe3, 0x63, 0xad, 0xce, 0x7c, 0x3e, 0xea, 0xd1, 0x65,
	0x62, 0xb6, 0xe4, 0x7c, 0xdc, 0x42, 0x7f, 0x19, 0x59, 0x03, 0x1c, 0xc5, 0x18, 0x3b, 0x53, 0x1c,
	0x61, 0xa6, 0x57, 0xfe, 0xe2, 0x50, 0x2f, 0xa6, 0x99, 0x5e, 0xa1, 0x5d, 0x40, 0xd3, 0xe2, 0xea,
	0xfd, 0xaf, 0x42, 0xf0, 0x1b, 0xb1, 0x35, 0x5c, 0xcf, 0xd5, 0x4e, 0x75, 0xaf, 0xf9, 0xe6, 0xb9,
	0xaa, 0xce, 0x6c, 0xca, 0x6e, 0xea, 0x75, 0x18, 0xd1, 0x78, 0x65, 0x67, 0x41, 0xed, 0x11, 0x68,
	0x69, 0x43, 0x70, 0x07, 0x54, 0x6f, 0xf0, 0x4a, 0xaa, 0x83, 0xbd, 0xc2, 0x97, 0xa0, 0xf6, 0x8b,
	0x17, 0x2c, 0x85, 0x2e, 0x6e, 0x93, 0xbf, 0x18, 0x7e, 0x5b, 0xf9, 0xd2, 0x40, 0xbf, 0xd7, 0xe5,
	0x47, 0xc9, 0x99, 0x88, 0xbe, 0xda, 0xf4, 0x82, 0xbf, 0x5d, 0x5b, 0xf0, 0x27, 0x6a, 0x3e, 0xca,
	0xa4, 0x65, 0x4b, 0x86, 0x0e, 0x78, 0x92, 0xbe, 0x0b, 0x77, 0x73, 0x8b, 0x13, 0xbd, 0xbe, 0x8f,
	0x48, 0x60, 0x82, 0xae, 0x40, 0xc1, 0x56, 0xd8, 0x5b, 0xc6, 0x31, 0x8e, 0x68, 0x9a, 0xbc, 0x10,
	0x7a, 0x01, 0x65, 0x2b, 0xbc, 0xf0, 0xa3, 0x24, 0x75, 0xaa, 0x8b, 0x15, 0x2a, 0x90, 0x50, 0xf4,
	0x32, 0x9a, 0x25, 0xa9, 0xd2, 0x85, 0x05, 0x8f, 0x01, 0x48, 0xe7, 0x3c, 0xb1, 0xcc, 0x06, 0x4f,
	0xf9, 0xd3, 0xfb, 0x52, 0x3e, 0xb1, 0x44, 0xba, 0x4a, 0xa8, 0x4a, 0x34, 0xb6, 0xcc, 0xed, 0x87,
	0x11, 0x8d, 0x8b, 0x44, 0x63, 0x6b, 0xc3, 0xda, 0x69, 0x7f, 0x0f, 0x9e, 0xdd, 0x52, 0xe9, 0x5b,
	0x48, 0x5f, 0xeb, 0xa4, 0xff, 0xcf, 0x49, 0x59, 0xac, 0x4c, 0x5f, 0x65, 0x7e, 0x07, 0x9e, 0x16,
	0x0a, 0x72, 0x0b, 0xeb, 0xae, 0xca, 0xda, 0x28, 0x09, 0x1f, 0xff, 0xfb, 0x70, 0xf4, 0x56, 0x7e,
	0x01, 0x94, 0xe4, 0x98, 0x5c, 0x0a, 0x1a, 0x34, 0xf8, 0xdf, 0xa8, 0x80, 0xa2, 0x3f, 0xab, 0xe2,
	0xd7, 0x36, 0x71, 0x26, 0xae, 0xb5, 0xe9, 0x5e, 0x7a, 0xb7, 0xd6, 0x4b, 0x1f, 0xab, 0xfb, 0x23,
	0x27, 0x2c, 0xed, 0xa3, 0x5e, 0xae, 0x23, 0xd7, 0x92, 0x3d, 0xf4, 0xfc, 0x2e, 0x02, 0xb7, 0xa8,
	0x21, 0xd7, 0xfa, 0xef, 0xfb, 0x66, 0xd3, 0x2a, 0xbd, 0xc8, 0xc5, 0xe0, 0x96, 0x8a, 0xa1, 0xab,
	0x13, 0x9a, 0x2a, 0xe1, 0x90, 0x50, 0x8a, 0xe3, 0x95, 0x45, 0x6e, 0xf4, 0x4f, 0xe7, 0x85, 0x72,
	0xb6, 0xc9, 0x3d, 0xd8, 0x61, 0x89, 0xbf, 0xb8, 0xab, 0x45, 0x76, 0x58, 0xca, 0x00, 0xf6, 0x3b,
	0x53, 0xbd, 0xe5, 0x99, 0x46, 0xc3, 0xd0, 0x8f, 0xd9, 0x1f, 0x28, 0x17, 0xc7, 0x7a, 0xd9, 0x8d,
	0x87, 0x94, 0xbd, 0xb2, 0x56, 0x76, 0xf4, 0x9b, 0x91, 0x7d, 0xf1, 0x39, 0x7d, 0xe9, 0xf7, 0xb0,
	0x74, 0x82, 0x0c, 0xf1, 0x17, 0xe9, 0x04, 0x0a, 0x04, 0x5f, 0x80, 0x96, 0x34, 0xe5, 0xf6, 0x56,
	0xb9, 0x8f, 0x0e, 0xa2, 0x2f, 0xb2, 0xea, 0xb1, 0x47, 0x8f, 0x44, 0xd3, 0x60, 0x39, 0xe3, 0x27,
	0xbe, 0x0b, 0x3f, 0xd2, 0x53, 0x50, 0x10, 0xf4, 0x87, 0x21, 0x0f, 0xac, 0x8e, 0x3c, 0x03, 0x97,
	0x1f, 0xa5, 0xe0, 0x49, 0x2e, 0xa4, 0xbc, 0xd8, 0x85, 0xff, 0x8f, 0x20, 0xe9, 0x6a, 0x7e, 0x42,
	0xf4, 0x7a, 0x6c, 0xfb, 0x07, 0x00, 0xd7, 0x9d, 0x36, 0xa4, 0xa4, 0x57, 0xda, 0x9a, 0xc6, 0x77,
	0x5d, 0x01, 0xc6, 0x9a, 0xeb, 0x81, 0x75, 0x5f, 0xc1, 0xd8, 0x7e, 0x0d, 0x49, 0x82, 0x0b, 0x82,
	0x50, 0x20, 0x34, 0x90, 0x77, 0x06, 0x47, 0xbd, 0x33, 0x94, 0x57, 0x55, 0xbd, 0x4d, 0x54, 0x0a,
	0xb7, 0x09, 0x5f, 0xcb, 0xce, 0xbd, 0x6b, 0x73, 0xbe, 0x5e, 0xdf, 0x9c, 0xbb, 0xeb, 0xa5, 0xbb,
	0x5f, 0xd6, 0xf9, 0x95, 0xf1, 0xf3, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x29, 0x55, 0xd4, 0x08,
	0x43, 0x0e, 0x00, 0x00,
}
