// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cmd.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登陆消息
type Game_C_TokenLogin struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token"`
	MachineID            string   `protobuf:"bytes,2,opt,name=MachineID,proto3" json:"MachineID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_TokenLogin) Reset()         { *m = Game_C_TokenLogin{} }
func (m *Game_C_TokenLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_TokenLogin) ProtoMessage()    {}
func (*Game_C_TokenLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{0}
}

func (m *Game_C_TokenLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_TokenLogin.Unmarshal(m, b)
}
func (m *Game_C_TokenLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_TokenLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_TokenLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_TokenLogin.Merge(m, src)
}
func (m *Game_C_TokenLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_TokenLogin.Size(m)
}
func (m *Game_C_TokenLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_TokenLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_TokenLogin proto.InternalMessageInfo

func (m *Game_C_TokenLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Game_C_TokenLogin) GetMachineID() string {
	if m != nil {
		return m.MachineID
	}
	return ""
}

//机器人登陆
type Game_C_RobotLogin struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID"`
	BatchID              int32    `protobuf:"varint,2,opt,name=BatchID,proto3" json:"BatchID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_RobotLogin) Reset()         { *m = Game_C_RobotLogin{} }
func (m *Game_C_RobotLogin) String() string { return proto.CompactTextString(m) }
func (*Game_C_RobotLogin) ProtoMessage()    {}
func (*Game_C_RobotLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{1}
}

func (m *Game_C_RobotLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_RobotLogin.Unmarshal(m, b)
}
func (m *Game_C_RobotLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_RobotLogin.Marshal(b, m, deterministic)
}
func (m *Game_C_RobotLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_RobotLogin.Merge(m, src)
}
func (m *Game_C_RobotLogin) XXX_Size() int {
	return xxx_messageInfo_Game_C_RobotLogin.Size(m)
}
func (m *Game_C_RobotLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_RobotLogin.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_RobotLogin proto.InternalMessageInfo

func (m *Game_C_RobotLogin) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_C_RobotLogin) GetBatchID() int32 {
	if m != nil {
		return m.BatchID
	}
	return 0
}

//用户坐下
type Game_C_UserSitDown struct {
	TableID              int32    `protobuf:"varint,1,opt,name=TableID,proto3" json:"TableID"`
	ChairID              int32    `protobuf:"varint,2,opt,name=ChairID,proto3" json:"ChairID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserSitDown) Reset()         { *m = Game_C_UserSitDown{} }
func (m *Game_C_UserSitDown) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserSitDown) ProtoMessage()    {}
func (*Game_C_UserSitDown) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{2}
}

func (m *Game_C_UserSitDown) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserSitDown.Unmarshal(m, b)
}
func (m *Game_C_UserSitDown) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserSitDown.Marshal(b, m, deterministic)
}
func (m *Game_C_UserSitDown) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserSitDown.Merge(m, src)
}
func (m *Game_C_UserSitDown) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserSitDown.Size(m)
}
func (m *Game_C_UserSitDown) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserSitDown.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserSitDown proto.InternalMessageInfo

func (m *Game_C_UserSitDown) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_C_UserSitDown) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//用户起立
type Game_C_UserStandUp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserStandUp) Reset()         { *m = Game_C_UserStandUp{} }
func (m *Game_C_UserStandUp) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserStandUp) ProtoMessage()    {}
func (*Game_C_UserStandUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{3}
}

func (m *Game_C_UserStandUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserStandUp.Unmarshal(m, b)
}
func (m *Game_C_UserStandUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserStandUp.Marshal(b, m, deterministic)
}
func (m *Game_C_UserStandUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserStandUp.Merge(m, src)
}
func (m *Game_C_UserStandUp) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserStandUp.Size(m)
}
func (m *Game_C_UserStandUp) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserStandUp.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserStandUp proto.InternalMessageInfo

//用户抢庄
type Game_C_UserQZ struct {
	Multiple             int32    `protobuf:"varint,1,opt,name=Multiple,proto3" json:"Multiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserQZ) Reset()         { *m = Game_C_UserQZ{} }
func (m *Game_C_UserQZ) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserQZ) ProtoMessage()    {}
func (*Game_C_UserQZ) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{4}
}

func (m *Game_C_UserQZ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserQZ.Unmarshal(m, b)
}
func (m *Game_C_UserQZ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserQZ.Marshal(b, m, deterministic)
}
func (m *Game_C_UserQZ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserQZ.Merge(m, src)
}
func (m *Game_C_UserQZ) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserQZ.Size(m)
}
func (m *Game_C_UserQZ) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserQZ.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserQZ proto.InternalMessageInfo

func (m *Game_C_UserQZ) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//用户下注
type Game_C_UserJetton struct {
	Multiple             int32    `protobuf:"varint,1,opt,name=Multiple,proto3" json:"Multiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserJetton) Reset()         { *m = Game_C_UserJetton{} }
func (m *Game_C_UserJetton) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserJetton) ProtoMessage()    {}
func (*Game_C_UserJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{5}
}

func (m *Game_C_UserJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserJetton.Unmarshal(m, b)
}
func (m *Game_C_UserJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserJetton.Marshal(b, m, deterministic)
}
func (m *Game_C_UserJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserJetton.Merge(m, src)
}
func (m *Game_C_UserJetton) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserJetton.Size(m)
}
func (m *Game_C_UserJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserJetton proto.InternalMessageInfo

func (m *Game_C_UserJetton) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//用户摊牌
type Game_C_UserTP struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_C_UserTP) Reset()         { *m = Game_C_UserTP{} }
func (m *Game_C_UserTP) String() string { return proto.CompactTextString(m) }
func (*Game_C_UserTP) ProtoMessage()    {}
func (*Game_C_UserTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{6}
}

func (m *Game_C_UserTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_C_UserTP.Unmarshal(m, b)
}
func (m *Game_C_UserTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_C_UserTP.Marshal(b, m, deterministic)
}
func (m *Game_C_UserTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_C_UserTP.Merge(m, src)
}
func (m *Game_C_UserTP) XXX_Size() int {
	return xxx_messageInfo_Game_C_UserTP.Size(m)
}
func (m *Game_C_UserTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_C_UserTP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_C_UserTP proto.InternalMessageInfo

//请求失败
type Game_S_ReqlyFail struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=ErrorCode,proto3" json:"ErrorCode"`
	ErrorMsg             string   `protobuf:"bytes,2,opt,name=ErrorMsg,proto3" json:"ErrorMsg"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_ReqlyFail) Reset()         { *m = Game_S_ReqlyFail{} }
func (m *Game_S_ReqlyFail) String() string { return proto.CompactTextString(m) }
func (*Game_S_ReqlyFail) ProtoMessage()    {}
func (*Game_S_ReqlyFail) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{7}
}

func (m *Game_S_ReqlyFail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_ReqlyFail.Unmarshal(m, b)
}
func (m *Game_S_ReqlyFail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_ReqlyFail.Marshal(b, m, deterministic)
}
func (m *Game_S_ReqlyFail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_ReqlyFail.Merge(m, src)
}
func (m *Game_S_ReqlyFail) XXX_Size() int {
	return xxx_messageInfo_Game_S_ReqlyFail.Size(m)
}
func (m *Game_S_ReqlyFail) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_ReqlyFail.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_ReqlyFail proto.InternalMessageInfo

func (m *Game_S_ReqlyFail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Game_S_ReqlyFail) GetErrorMsg() string {
	if m != nil {
		return m.ErrorMsg
	}
	return ""
}

//登陆成功
type Game_S_LoginSuccess struct {
	GameQZTime           int32    `protobuf:"varint,1,opt,name=GameQZTime,proto3" json:"GameQZTime"`
	GameJettonTime       int32    `protobuf:"varint,2,opt,name=GameJettonTime,proto3" json:"GameJettonTime"`
	GameTPTime           int32    `protobuf:"varint,3,opt,name=GameTPTime,proto3" json:"GameTPTime"`
	MultipleList         []int32  `protobuf:"varint,4,rep,packed,name=MultipleList,proto3" json:"MultipleList"`
	JettonList           []int32  `protobuf:"varint,5,rep,packed,name=JettonList,proto3" json:"JettonList"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LoginSuccess) Reset()         { *m = Game_S_LoginSuccess{} }
func (m *Game_S_LoginSuccess) String() string { return proto.CompactTextString(m) }
func (*Game_S_LoginSuccess) ProtoMessage()    {}
func (*Game_S_LoginSuccess) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{8}
}

func (m *Game_S_LoginSuccess) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LoginSuccess.Unmarshal(m, b)
}
func (m *Game_S_LoginSuccess) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LoginSuccess.Marshal(b, m, deterministic)
}
func (m *Game_S_LoginSuccess) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LoginSuccess.Merge(m, src)
}
func (m *Game_S_LoginSuccess) XXX_Size() int {
	return xxx_messageInfo_Game_S_LoginSuccess.Size(m)
}
func (m *Game_S_LoginSuccess) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LoginSuccess.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LoginSuccess proto.InternalMessageInfo

func (m *Game_S_LoginSuccess) GetGameQZTime() int32 {
	if m != nil {
		return m.GameQZTime
	}
	return 0
}

func (m *Game_S_LoginSuccess) GetGameJettonTime() int32 {
	if m != nil {
		return m.GameJettonTime
	}
	return 0
}

func (m *Game_S_LoginSuccess) GetGameTPTime() int32 {
	if m != nil {
		return m.GameTPTime
	}
	return 0
}

func (m *Game_S_LoginSuccess) GetMultipleList() []int32 {
	if m != nil {
		return m.MultipleList
	}
	return nil
}

func (m *Game_S_LoginSuccess) GetJettonList() []int32 {
	if m != nil {
		return m.JettonList
	}
	return nil
}

//坐下通知消息
type Game_S_SitDownNotify struct {
	Data                 *Game_S_User `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Game_S_SitDownNotify) Reset()         { *m = Game_S_SitDownNotify{} }
func (m *Game_S_SitDownNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_SitDownNotify) ProtoMessage()    {}
func (*Game_S_SitDownNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{9}
}

func (m *Game_S_SitDownNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_SitDownNotify.Unmarshal(m, b)
}
func (m *Game_S_SitDownNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_SitDownNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_SitDownNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_SitDownNotify.Merge(m, src)
}
func (m *Game_S_SitDownNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_SitDownNotify.Size(m)
}
func (m *Game_S_SitDownNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_SitDownNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_SitDownNotify proto.InternalMessageInfo

func (m *Game_S_SitDownNotify) GetData() *Game_S_User {
	if m != nil {
		return m.Data
	}
	return nil
}

//user
type Game_S_User struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID"`
	NikeName             string   `protobuf:"bytes,2,opt,name=NikeName,proto3" json:"NikeName"`
	UserGold             float32  `protobuf:"fixed32,3,opt,name=UserGold,proto3" json:"UserGold"`
	UserDiamond          float32  `protobuf:"fixed32,4,opt,name=UserDiamond,proto3" json:"UserDiamond"`
	MemberOrder          int32    `protobuf:"varint,5,opt,name=MemberOrder,proto3" json:"MemberOrder"`
	HeadImageUrl         string   `protobuf:"bytes,6,opt,name=HeadImageUrl,proto3" json:"HeadImageUrl"`
	FaceID               int32    `protobuf:"varint,7,opt,name=FaceID,proto3" json:"FaceID"`
	RoleID               int32    `protobuf:"varint,8,opt,name=RoleID,proto3" json:"RoleID"`
	SuitID               int32    `protobuf:"varint,9,opt,name=SuitID,proto3" json:"SuitID"`
	PhotoFrameID         int32    `protobuf:"varint,10,opt,name=PhotoFrameID,proto3" json:"PhotoFrameID"`
	TableID              int32    `protobuf:"varint,11,opt,name=TableID,proto3" json:"TableID"`
	ChairID              int32    `protobuf:"varint,12,opt,name=ChairID,proto3" json:"ChairID"`
	Status               int32    `protobuf:"varint,13,opt,name=Status,proto3" json:"Status"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_User) Reset()         { *m = Game_S_User{} }
func (m *Game_S_User) String() string { return proto.CompactTextString(m) }
func (*Game_S_User) ProtoMessage()    {}
func (*Game_S_User) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{10}
}

func (m *Game_S_User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_User.Unmarshal(m, b)
}
func (m *Game_S_User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_User.Marshal(b, m, deterministic)
}
func (m *Game_S_User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_User.Merge(m, src)
}
func (m *Game_S_User) XXX_Size() int {
	return xxx_messageInfo_Game_S_User.Size(m)
}
func (m *Game_S_User) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_User.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_User proto.InternalMessageInfo

func (m *Game_S_User) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *Game_S_User) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *Game_S_User) GetUserGold() float32 {
	if m != nil {
		return m.UserGold
	}
	return 0
}

func (m *Game_S_User) GetUserDiamond() float32 {
	if m != nil {
		return m.UserDiamond
	}
	return 0
}

func (m *Game_S_User) GetMemberOrder() int32 {
	if m != nil {
		return m.MemberOrder
	}
	return 0
}

func (m *Game_S_User) GetHeadImageUrl() string {
	if m != nil {
		return m.HeadImageUrl
	}
	return ""
}

func (m *Game_S_User) GetFaceID() int32 {
	if m != nil {
		return m.FaceID
	}
	return 0
}

func (m *Game_S_User) GetRoleID() int32 {
	if m != nil {
		return m.RoleID
	}
	return 0
}

func (m *Game_S_User) GetSuitID() int32 {
	if m != nil {
		return m.SuitID
	}
	return 0
}

func (m *Game_S_User) GetPhotoFrameID() int32 {
	if m != nil {
		return m.PhotoFrameID
	}
	return 0
}

func (m *Game_S_User) GetTableID() int32 {
	if m != nil {
		return m.TableID
	}
	return 0
}

func (m *Game_S_User) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_User) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

//起立通知消息
type Game_S_StandUpNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StandUpNotify) Reset()         { *m = Game_S_StandUpNotify{} }
func (m *Game_S_StandUpNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_StandUpNotify) ProtoMessage()    {}
func (*Game_S_StandUpNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{11}
}

func (m *Game_S_StandUpNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StandUpNotify.Unmarshal(m, b)
}
func (m *Game_S_StandUpNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StandUpNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_StandUpNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StandUpNotify.Merge(m, src)
}
func (m *Game_S_StandUpNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_StandUpNotify.Size(m)
}
func (m *Game_S_StandUpNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StandUpNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StandUpNotify proto.InternalMessageInfo

func (m *Game_S_StandUpNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//掉线通知消息
type Game_S_OffLineNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_OffLineNotify) Reset()         { *m = Game_S_OffLineNotify{} }
func (m *Game_S_OffLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OffLineNotify) ProtoMessage()    {}
func (*Game_S_OffLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{12}
}

func (m *Game_S_OffLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OffLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OffLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OffLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OffLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OffLineNotify.Merge(m, src)
}
func (m *Game_S_OffLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OffLineNotify.Size(m)
}
func (m *Game_S_OffLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OffLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OffLineNotify proto.InternalMessageInfo

func (m *Game_S_OffLineNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//上线通知消息
type Game_S_OnLineNotify struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_OnLineNotify) Reset()         { *m = Game_S_OnLineNotify{} }
func (m *Game_S_OnLineNotify) String() string { return proto.CompactTextString(m) }
func (*Game_S_OnLineNotify) ProtoMessage()    {}
func (*Game_S_OnLineNotify) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{13}
}

func (m *Game_S_OnLineNotify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_OnLineNotify.Unmarshal(m, b)
}
func (m *Game_S_OnLineNotify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_OnLineNotify.Marshal(b, m, deterministic)
}
func (m *Game_S_OnLineNotify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_OnLineNotify.Merge(m, src)
}
func (m *Game_S_OnLineNotify) XXX_Size() int {
	return xxx_messageInfo_Game_S_OnLineNotify.Size(m)
}
func (m *Game_S_OnLineNotify) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_OnLineNotify.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_OnLineNotify proto.InternalMessageInfo

func (m *Game_S_OnLineNotify) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//空闲场景
type Game_S_FreeScene struct {
	SceneStartTime       int64                  `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime"`
	UserChairID          int32                  `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_FreeScene) Reset()         { *m = Game_S_FreeScene{} }
func (m *Game_S_FreeScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_FreeScene) ProtoMessage()    {}
func (*Game_S_FreeScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{14}
}

func (m *Game_S_FreeScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_FreeScene.Unmarshal(m, b)
}
func (m *Game_S_FreeScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_FreeScene.Marshal(b, m, deterministic)
}
func (m *Game_S_FreeScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_FreeScene.Merge(m, src)
}
func (m *Game_S_FreeScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_FreeScene.Size(m)
}
func (m *Game_S_FreeScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_FreeScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_FreeScene proto.InternalMessageInfo

func (m *Game_S_FreeScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_FreeScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_FreeScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

//抢庄场景
type Game_S_QZScene struct {
	SceneStartTime       int64                  `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime"`
	UserChairID          int32                  `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserListQZ           map[int32]int32        `protobuf:"bytes,4,rep,name=UserListQZ,proto3" json:"UserListQZ" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_QZScene) Reset()         { *m = Game_S_QZScene{} }
func (m *Game_S_QZScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_QZScene) ProtoMessage()    {}
func (*Game_S_QZScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{15}
}

func (m *Game_S_QZScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_QZScene.Unmarshal(m, b)
}
func (m *Game_S_QZScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_QZScene.Marshal(b, m, deterministic)
}
func (m *Game_S_QZScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_QZScene.Merge(m, src)
}
func (m *Game_S_QZScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_QZScene.Size(m)
}
func (m *Game_S_QZScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_QZScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_QZScene proto.InternalMessageInfo

func (m *Game_S_QZScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_QZScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_QZScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_QZScene) GetUserListQZ() map[int32]int32 {
	if m != nil {
		return m.UserListQZ
	}
	return nil
}

//下注场景
type Game_S_JettonScene struct {
	SceneStartTime       int64                  `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime"`
	UserChairID          int32                  `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID"`
	UserList             map[int32]*Game_S_User `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserListJetton       map[int32]int32        `protobuf:"bytes,4,rep,name=UserListJetton,proto3" json:"UserListJetton" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	BankerChairID        int32                  `protobuf:"varint,5,opt,name=BankerChairID,proto3" json:"BankerChairID"`
	BankerMultiple       int32                  `protobuf:"varint,6,opt,name=BankerMultiple,proto3" json:"BankerMultiple"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Game_S_JettonScene) Reset()         { *m = Game_S_JettonScene{} }
func (m *Game_S_JettonScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_JettonScene) ProtoMessage()    {}
func (*Game_S_JettonScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{16}
}

func (m *Game_S_JettonScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_JettonScene.Unmarshal(m, b)
}
func (m *Game_S_JettonScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_JettonScene.Marshal(b, m, deterministic)
}
func (m *Game_S_JettonScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_JettonScene.Merge(m, src)
}
func (m *Game_S_JettonScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_JettonScene.Size(m)
}
func (m *Game_S_JettonScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_JettonScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_JettonScene proto.InternalMessageInfo

func (m *Game_S_JettonScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_JettonScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_JettonScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_JettonScene) GetUserListJetton() map[int32]int32 {
	if m != nil {
		return m.UserListJetton
	}
	return nil
}

func (m *Game_S_JettonScene) GetBankerChairID() int32 {
	if m != nil {
		return m.BankerChairID
	}
	return 0
}

func (m *Game_S_JettonScene) GetBankerMultiple() int32 {
	if m != nil {
		return m.BankerMultiple
	}
	return 0
}

//摊牌场景
type Game_S_TPScene struct {
	SceneStartTime       int64                          `protobuf:"zigzag64,1,opt,name=SceneStartTime,proto3" json:"SceneStartTime"`
	UserChairID          int32                          `protobuf:"varint,2,opt,name=UserChairID,proto3" json:"UserChairID"`
	UserList             map[int32]*Game_S_User         `protobuf:"bytes,3,rep,name=UserList,proto3" json:"UserList" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UserListTP           map[int32]*Game_S_LotteryPoker `protobuf:"bytes,4,rep,name=UserListTP,proto3" json:"UserListTP" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	BankerChairID        int32                          `protobuf:"varint,5,opt,name=BankerChairID,proto3" json:"BankerChairID"`
	BankerMultiple       int32                          `protobuf:"varint,6,opt,name=BankerMultiple,proto3" json:"BankerMultiple"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *Game_S_TPScene) Reset()         { *m = Game_S_TPScene{} }
func (m *Game_S_TPScene) String() string { return proto.CompactTextString(m) }
func (*Game_S_TPScene) ProtoMessage()    {}
func (*Game_S_TPScene) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{17}
}

func (m *Game_S_TPScene) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_TPScene.Unmarshal(m, b)
}
func (m *Game_S_TPScene) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_TPScene.Marshal(b, m, deterministic)
}
func (m *Game_S_TPScene) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_TPScene.Merge(m, src)
}
func (m *Game_S_TPScene) XXX_Size() int {
	return xxx_messageInfo_Game_S_TPScene.Size(m)
}
func (m *Game_S_TPScene) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_TPScene.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_TPScene proto.InternalMessageInfo

func (m *Game_S_TPScene) GetSceneStartTime() int64 {
	if m != nil {
		return m.SceneStartTime
	}
	return 0
}

func (m *Game_S_TPScene) GetUserChairID() int32 {
	if m != nil {
		return m.UserChairID
	}
	return 0
}

func (m *Game_S_TPScene) GetUserList() map[int32]*Game_S_User {
	if m != nil {
		return m.UserList
	}
	return nil
}

func (m *Game_S_TPScene) GetUserListTP() map[int32]*Game_S_LotteryPoker {
	if m != nil {
		return m.UserListTP
	}
	return nil
}

func (m *Game_S_TPScene) GetBankerChairID() int32 {
	if m != nil {
		return m.BankerChairID
	}
	return 0
}

func (m *Game_S_TPScene) GetBankerMultiple() int32 {
	if m != nil {
		return m.BankerMultiple
	}
	return 0
}

type Game_S_LotteryPoker struct {
	PokerType            int32    `protobuf:"varint,1,opt,name=PokerType,proto3" json:"PokerType"`
	LotteryPoker         []int32  `protobuf:"varint,2,rep,packed,name=LotteryPoker,proto3" json:"LotteryPoker"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_LotteryPoker) Reset()         { *m = Game_S_LotteryPoker{} }
func (m *Game_S_LotteryPoker) String() string { return proto.CompactTextString(m) }
func (*Game_S_LotteryPoker) ProtoMessage()    {}
func (*Game_S_LotteryPoker) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{18}
}

func (m *Game_S_LotteryPoker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_LotteryPoker.Unmarshal(m, b)
}
func (m *Game_S_LotteryPoker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_LotteryPoker.Marshal(b, m, deterministic)
}
func (m *Game_S_LotteryPoker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_LotteryPoker.Merge(m, src)
}
func (m *Game_S_LotteryPoker) XXX_Size() int {
	return xxx_messageInfo_Game_S_LotteryPoker.Size(m)
}
func (m *Game_S_LotteryPoker) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_LotteryPoker.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_LotteryPoker proto.InternalMessageInfo

func (m *Game_S_LotteryPoker) GetPokerType() int32 {
	if m != nil {
		return m.PokerType
	}
	return 0
}

func (m *Game_S_LotteryPoker) GetLotteryPoker() []int32 {
	if m != nil {
		return m.LotteryPoker
	}
	return nil
}

//开始定时器
type Game_S_StartTime struct {
	GameStatus           int32    `protobuf:"varint,1,opt,name=GameStatus,proto3" json:"GameStatus"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_StartTime) Reset()         { *m = Game_S_StartTime{} }
func (m *Game_S_StartTime) String() string { return proto.CompactTextString(m) }
func (*Game_S_StartTime) ProtoMessage()    {}
func (*Game_S_StartTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{19}
}

func (m *Game_S_StartTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_StartTime.Unmarshal(m, b)
}
func (m *Game_S_StartTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_StartTime.Marshal(b, m, deterministic)
}
func (m *Game_S_StartTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_StartTime.Merge(m, src)
}
func (m *Game_S_StartTime) XXX_Size() int {
	return xxx_messageInfo_Game_S_StartTime.Size(m)
}
func (m *Game_S_StartTime) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_StartTime.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_StartTime proto.InternalMessageInfo

func (m *Game_S_StartTime) GetGameStatus() int32 {
	if m != nil {
		return m.GameStatus
	}
	return 0
}

//结束游戏消息
type Game_S_GameConclude struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_GameConclude) Reset()         { *m = Game_S_GameConclude{} }
func (m *Game_S_GameConclude) String() string { return proto.CompactTextString(m) }
func (*Game_S_GameConclude) ProtoMessage()    {}
func (*Game_S_GameConclude) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{20}
}

func (m *Game_S_GameConclude) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GameConclude.Unmarshal(m, b)
}
func (m *Game_S_GameConclude) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GameConclude.Marshal(b, m, deterministic)
}
func (m *Game_S_GameConclude) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GameConclude.Merge(m, src)
}
func (m *Game_S_GameConclude) XXX_Size() int {
	return xxx_messageInfo_Game_S_GameConclude.Size(m)
}
func (m *Game_S_GameConclude) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GameConclude.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GameConclude proto.InternalMessageInfo

//抢庄通知
type Game_S_UserQZ struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	Multiple             int32    `protobuf:"varint,2,opt,name=Multiple,proto3" json:"Multiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserQZ) Reset()         { *m = Game_S_UserQZ{} }
func (m *Game_S_UserQZ) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserQZ) ProtoMessage()    {}
func (*Game_S_UserQZ) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{21}
}

func (m *Game_S_UserQZ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserQZ.Unmarshal(m, b)
}
func (m *Game_S_UserQZ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserQZ.Marshal(b, m, deterministic)
}
func (m *Game_S_UserQZ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserQZ.Merge(m, src)
}
func (m *Game_S_UserQZ) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserQZ.Size(m)
}
func (m *Game_S_UserQZ) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserQZ.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserQZ proto.InternalMessageInfo

func (m *Game_S_UserQZ) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserQZ) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//定庄通知
type Game_S_GameDZ struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_GameDZ) Reset()         { *m = Game_S_GameDZ{} }
func (m *Game_S_GameDZ) String() string { return proto.CompactTextString(m) }
func (*Game_S_GameDZ) ProtoMessage()    {}
func (*Game_S_GameDZ) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{22}
}

func (m *Game_S_GameDZ) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_GameDZ.Unmarshal(m, b)
}
func (m *Game_S_GameDZ) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_GameDZ.Marshal(b, m, deterministic)
}
func (m *Game_S_GameDZ) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_GameDZ.Merge(m, src)
}
func (m *Game_S_GameDZ) XXX_Size() int {
	return xxx_messageInfo_Game_S_GameDZ.Size(m)
}
func (m *Game_S_GameDZ) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_GameDZ.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_GameDZ proto.InternalMessageInfo

func (m *Game_S_GameDZ) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

//下注通知
type Game_S_UserJetton struct {
	ChairID              int32    `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	Multiple             int32    `protobuf:"varint,2,opt,name=Multiple,proto3" json:"Multiple"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Game_S_UserJetton) Reset()         { *m = Game_S_UserJetton{} }
func (m *Game_S_UserJetton) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserJetton) ProtoMessage()    {}
func (*Game_S_UserJetton) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{23}
}

func (m *Game_S_UserJetton) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserJetton.Unmarshal(m, b)
}
func (m *Game_S_UserJetton) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserJetton.Marshal(b, m, deterministic)
}
func (m *Game_S_UserJetton) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserJetton.Merge(m, src)
}
func (m *Game_S_UserJetton) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserJetton.Size(m)
}
func (m *Game_S_UserJetton) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserJetton.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserJetton proto.InternalMessageInfo

func (m *Game_S_UserJetton) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserJetton) GetMultiple() int32 {
	if m != nil {
		return m.Multiple
	}
	return 0
}

//摊牌通知
type Game_S_UserTP struct {
	ChairID              int32                `protobuf:"varint,1,opt,name=ChairID,proto3" json:"ChairID"`
	Poker                *Game_S_LotteryPoker `protobuf:"bytes,2,opt,name=Poker,proto3" json:"Poker"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Game_S_UserTP) Reset()         { *m = Game_S_UserTP{} }
func (m *Game_S_UserTP) String() string { return proto.CompactTextString(m) }
func (*Game_S_UserTP) ProtoMessage()    {}
func (*Game_S_UserTP) Descriptor() ([]byte, []int) {
	return fileDescriptor_7520252fb01eaf30, []int{24}
}

func (m *Game_S_UserTP) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game_S_UserTP.Unmarshal(m, b)
}
func (m *Game_S_UserTP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game_S_UserTP.Marshal(b, m, deterministic)
}
func (m *Game_S_UserTP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game_S_UserTP.Merge(m, src)
}
func (m *Game_S_UserTP) XXX_Size() int {
	return xxx_messageInfo_Game_S_UserTP.Size(m)
}
func (m *Game_S_UserTP) XXX_DiscardUnknown() {
	xxx_messageInfo_Game_S_UserTP.DiscardUnknown(m)
}

var xxx_messageInfo_Game_S_UserTP proto.InternalMessageInfo

func (m *Game_S_UserTP) GetChairID() int32 {
	if m != nil {
		return m.ChairID
	}
	return 0
}

func (m *Game_S_UserTP) GetPoker() *Game_S_LotteryPoker {
	if m != nil {
		return m.Poker
	}
	return nil
}

func init() {
	proto.RegisterType((*Game_C_TokenLogin)(nil), "msg.Game_C_TokenLogin")
	proto.RegisterType((*Game_C_RobotLogin)(nil), "msg.Game_C_RobotLogin")
	proto.RegisterType((*Game_C_UserSitDown)(nil), "msg.Game_C_UserSitDown")
	proto.RegisterType((*Game_C_UserStandUp)(nil), "msg.Game_C_UserStandUp")
	proto.RegisterType((*Game_C_UserQZ)(nil), "msg.Game_C_UserQZ")
	proto.RegisterType((*Game_C_UserJetton)(nil), "msg.Game_C_UserJetton")
	proto.RegisterType((*Game_C_UserTP)(nil), "msg.Game_C_UserTP")
	proto.RegisterType((*Game_S_ReqlyFail)(nil), "msg.Game_S_ReqlyFail")
	proto.RegisterType((*Game_S_LoginSuccess)(nil), "msg.Game_S_LoginSuccess")
	proto.RegisterType((*Game_S_SitDownNotify)(nil), "msg.Game_S_SitDownNotify")
	proto.RegisterType((*Game_S_User)(nil), "msg.Game_S_User")
	proto.RegisterType((*Game_S_StandUpNotify)(nil), "msg.Game_S_StandUpNotify")
	proto.RegisterType((*Game_S_OffLineNotify)(nil), "msg.Game_S_OffLineNotify")
	proto.RegisterType((*Game_S_OnLineNotify)(nil), "msg.Game_S_OnLineNotify")
	proto.RegisterType((*Game_S_FreeScene)(nil), "msg.Game_S_FreeScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_FreeScene.UserListEntry")
	proto.RegisterType((*Game_S_QZScene)(nil), "msg.Game_S_QZScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_QZScene.UserListEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_QZScene.UserListQZEntry")
	proto.RegisterType((*Game_S_JettonScene)(nil), "msg.Game_S_JettonScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_JettonScene.UserListEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "msg.Game_S_JettonScene.UserListJettonEntry")
	proto.RegisterType((*Game_S_TPScene)(nil), "msg.Game_S_TPScene")
	proto.RegisterMapType((map[int32]*Game_S_User)(nil), "msg.Game_S_TPScene.UserListEntry")
	proto.RegisterMapType((map[int32]*Game_S_LotteryPoker)(nil), "msg.Game_S_TPScene.UserListTPEntry")
	proto.RegisterType((*Game_S_LotteryPoker)(nil), "msg.Game_S_LotteryPoker")
	proto.RegisterType((*Game_S_StartTime)(nil), "msg.Game_S_StartTime")
	proto.RegisterType((*Game_S_GameConclude)(nil), "msg.Game_S_GameConclude")
	proto.RegisterType((*Game_S_UserQZ)(nil), "msg.Game_S_UserQZ")
	proto.RegisterType((*Game_S_GameDZ)(nil), "msg.Game_S_GameDZ")
	proto.RegisterType((*Game_S_UserJetton)(nil), "msg.Game_S_UserJetton")
	proto.RegisterType((*Game_S_UserTP)(nil), "msg.Game_S_UserTP")
}

func init() { proto.RegisterFile("cmd.proto", fileDescriptor_7520252fb01eaf30) }

var fileDescriptor_7520252fb01eaf30 = []byte{
	// 953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xef, 0x6e, 0xdb, 0x36,
	0x10, 0x87, 0xed, 0x28, 0x8d, 0xe9, 0xa6, 0xcd, 0xd8, 0x6c, 0x10, 0x82, 0x61, 0xc8, 0xb8, 0xae,
	0xc8, 0x50, 0xc0, 0x1d, 0xb2, 0x2f, 0xc3, 0xb0, 0x62, 0x68, 0xed, 0x24, 0xf5, 0x60, 0x27, 0xb2,
	0xa4, 0xa0, 0x98, 0xbf, 0x18, 0x8c, 0xc4, 0x38, 0x82, 0x25, 0x31, 0x93, 0xe8, 0x0d, 0x7e, 0xbc,
	0xbd, 0xc3, 0xb0, 0xa7, 0xe8, 0x2b, 0x0c, 0x18, 0xf8, 0x47, 0x14, 0xa5, 0xda, 0x49, 0x37, 0x18,
	0x43, 0x3f, 0x89, 0xf7, 0xe3, 0xf1, 0x77, 0xbc, 0xe3, 0x1d, 0x79, 0x02, 0xed, 0x20, 0x09, 0xbb,
	0xb7, 0x19, 0x65, 0x14, 0xb6, 0x92, 0x7c, 0x86, 0xce, 0xc0, 0x27, 0x67, 0x38, 0x21, 0xd3, 0xde,
	0xd4, 0xa7, 0x73, 0x92, 0x0e, 0xe9, 0x2c, 0x4a, 0xe1, 0x3e, 0xb0, 0x84, 0x64, 0x37, 0x0e, 0x1b,
	0x47, 0x6d, 0x57, 0x0a, 0xf0, 0x73, 0xd0, 0x1e, 0xe1, 0xe0, 0x26, 0x4a, 0xc9, 0xa0, 0x6f, 0x37,
	0xc5, 0x4c, 0x09, 0xa0, 0x13, 0x4d, 0xe4, 0xd2, 0x2b, 0xca, 0x24, 0xd1, 0x67, 0x60, 0xfb, 0x32,
	0x27, 0xd9, 0xa0, 0x2f, 0x98, 0x2c, 0x57, 0x49, 0xd0, 0x06, 0x0f, 0x5e, 0x63, 0x16, 0xdc, 0x28,
	0x22, 0xcb, 0x2d, 0x44, 0xf4, 0x06, 0x40, 0x45, 0xc3, 0x55, 0xbd, 0x88, 0xf5, 0xe9, 0xef, 0x29,
	0xd7, 0xf7, 0xf1, 0x55, 0x4c, 0x34, 0x51, 0x21, 0xf2, 0x99, 0xde, 0x0d, 0x8e, 0xb2, 0x92, 0x49,
	0x89, 0x68, 0xbf, 0xca, 0xc4, 0x70, 0x1a, 0x5e, 0xde, 0xa2, 0xe7, 0x60, 0xd7, 0x40, 0xc7, 0x13,
	0x78, 0x00, 0x76, 0x46, 0x8b, 0x98, 0x45, 0xb7, 0x31, 0x51, 0xdc, 0x5a, 0x46, 0x2f, 0xb4, 0x4f,
	0x5c, 0xf9, 0x67, 0xc2, 0x18, 0x4d, 0xef, 0x5c, 0xf0, 0xb8, 0xc2, 0xee, 0x3b, 0x68, 0x08, 0xf6,
	0x04, 0xe0, 0x4d, 0x5d, 0xf2, 0x6b, 0xbc, 0x3c, 0xc5, 0x51, 0xcc, 0xe3, 0x78, 0x92, 0x65, 0x34,
	0xeb, 0xd1, 0xb0, 0x60, 0x28, 0x01, 0x4e, 0x2f, 0x84, 0x51, 0x3e, 0x53, 0x41, 0xd6, 0x32, 0xfa,
	0xa3, 0x01, 0x9e, 0x28, 0x3a, 0x11, 0x5f, 0x6f, 0x11, 0x04, 0x24, 0xcf, 0xe1, 0x17, 0x00, 0x70,
	0x78, 0x3c, 0xf1, 0xa3, 0xa4, 0xa0, 0x34, 0x10, 0xf8, 0x0c, 0x3c, 0xe2, 0x92, 0x74, 0x40, 0xe8,
	0xc8, 0x58, 0xd5, 0xd0, 0x82, 0xc7, 0x77, 0x84, 0x4e, 0xab, 0xe4, 0x91, 0x08, 0x44, 0xe0, 0x61,
	0xe1, 0xea, 0x30, 0xca, 0x99, 0xbd, 0x75, 0xd8, 0x3a, 0xb2, 0xdc, 0x0a, 0xc6, 0x39, 0x24, 0xa3,
	0xd0, 0xb0, 0x84, 0x86, 0x81, 0xa0, 0x1f, 0xc1, 0xbe, 0x72, 0x41, 0x1d, 0xee, 0x39, 0x65, 0xd1,
	0xf5, 0x12, 0x3e, 0x05, 0x5b, 0x7d, 0xcc, 0xb0, 0xd8, 0x7d, 0xe7, 0x78, 0xaf, 0x9b, 0xe4, 0xb3,
	0xae, 0x52, 0xe4, 0xb1, 0x74, 0xc5, 0x2c, 0xfa, 0xbb, 0x09, 0x3a, 0x06, 0xba, 0x36, 0xc1, 0x0e,
	0xc0, 0xce, 0x79, 0x34, 0x27, 0xe7, 0x58, 0xf9, 0xda, 0x76, 0xb5, 0xcc, 0xe7, 0xb8, 0xd6, 0x19,
	0x8d, 0x43, 0xe1, 0x63, 0xd3, 0xd5, 0x32, 0x3c, 0x04, 0x1d, 0x3e, 0xee, 0x47, 0x38, 0xa1, 0x69,
	0x68, 0x6f, 0x89, 0x69, 0x13, 0xe2, 0x1a, 0x23, 0x92, 0x5c, 0x91, 0xec, 0x22, 0x0b, 0x49, 0x66,
	0x5b, 0xc2, 0xac, 0x09, 0xf1, 0x28, 0xbd, 0x21, 0x38, 0x1c, 0x24, 0x78, 0x46, 0x2e, 0xb3, 0xd8,
	0xde, 0x16, 0xf6, 0x2b, 0x18, 0xdf, 0xf7, 0x29, 0x0e, 0x78, 0x3e, 0x3f, 0x90, 0xfb, 0x96, 0x12,
	0xc7, 0x5d, 0x2a, 0xf2, 0x7c, 0x47, 0xe2, 0x52, 0xe2, 0xb8, 0xb7, 0x88, 0xd8, 0xa0, 0x6f, 0xb7,
	0x25, 0x2e, 0x25, 0x6e, 0xcb, 0xb9, 0xa1, 0x8c, 0x9e, 0x66, 0x38, 0xe1, 0xab, 0x80, 0x98, 0xad,
	0x60, 0x66, 0xf1, 0x74, 0xd6, 0x16, 0xcf, 0xc3, 0x4a, 0xf1, 0x08, 0x7b, 0x0c, 0xb3, 0x45, 0x6e,
	0xef, 0x2a, 0x7b, 0x42, 0x42, 0xdf, 0x96, 0xa7, 0x27, 0x0b, 0x4a, 0x9d, 0x9e, 0xc1, 0xd4, 0xa8,
	0x96, 0x61, 0xb9, 0xe2, 0xe2, 0xfa, 0x7a, 0x18, 0xa5, 0xe4, 0xde, 0x15, 0x2f, 0x74, 0x92, 0x5f,
	0xa4, 0x1f, 0xb4, 0xe0, 0x5d, 0x43, 0x57, 0xd9, 0x69, 0x46, 0x88, 0x17, 0x90, 0x54, 0xe4, 0xbc,
	0x18, 0x78, 0x0c, 0x67, 0x4c, 0xd7, 0x05, 0x74, 0x6b, 0x68, 0x71, 0xe2, 0xd5, 0x4b, 0xc4, 0x84,
	0xe0, 0x4f, 0x32, 0x5f, 0x44, 0x3e, 0xb7, 0x0e, 0x5b, 0x47, 0x9d, 0xe3, 0xaf, 0xcc, 0xec, 0xd4,
	0x26, 0xbb, 0x85, 0xd6, 0x49, 0xca, 0xb2, 0xa5, 0xab, 0x17, 0x1d, 0x8c, 0xc0, 0x6e, 0x65, 0x0a,
	0xee, 0x81, 0xd6, 0x9c, 0x2c, 0x95, 0x1b, 0x7c, 0x08, 0x9f, 0x01, 0xeb, 0x37, 0x1c, 0x2f, 0x64,
	0xb2, 0xae, 0x4a, 0x7f, 0x39, 0xfd, 0x43, 0xf3, 0xfb, 0x06, 0x7a, 0xd7, 0x94, 0xe5, 0x3c, 0xf5,
	0xa6, 0xe3, 0xc9, 0xa6, 0x9d, 0x7d, 0xf9, 0x9e, 0xb3, 0x5f, 0x9a, 0x7b, 0x51, 0x06, 0xd7, 0xb9,
	0x0a, 0x7b, 0x00, 0x14, 0xe3, 0xf1, 0x44, 0xdc, 0x0f, 0xb5, 0x68, 0xd5, 0x09, 0xc6, 0x13, 0x49,
	0x61, 0x2c, 0xdb, 0x70, 0xbc, 0x0e, 0x5e, 0x82, 0xc7, 0x35, 0x6b, 0x2b, 0x08, 0xf7, 0x4d, 0x42,
	0xcb, 0x0c, 0xf7, 0x5f, 0x2d, 0xf5, 0x90, 0x78, 0x53, 0x79, 0x8d, 0x6d, 0x3a, 0xe4, 0xaf, 0xde,
	0x0b, 0xf9, 0xd7, 0xa6, 0x3b, 0x86, 0xd1, 0xb5, 0x61, 0xf7, 0xc0, 0xa3, 0x62, 0x2c, 0xd5, 0x55,
	0xe8, 0x9f, 0xdf, 0x47, 0x24, 0x31, 0x49, 0x57, 0xa3, 0x80, 0x4f, 0xc1, 0xee, 0x6b, 0x9c, 0xce,
	0xcb, 0xbd, 0xcb, 0xbb, 0xae, 0x0a, 0xf2, 0x38, 0x48, 0x40, 0x3f, 0x8a, 0xdb, 0xf2, 0x6d, 0xa9,
	0xa2, 0x9b, 0x3e, 0xd4, 0x57, 0xe0, 0xc9, 0x0a, 0x1f, 0xfe, 0xd5, 0xc1, 0xfe, 0xd9, 0xd2, 0x75,
	0xe4, 0x3b, 0xff, 0x73, 0x1d, 0x29, 0x83, 0x1f, 0x52, 0x47, 0xbe, 0xb3, 0xaa, 0x8e, 0xea, 0x04,
	0xbe, 0x53, 0xab, 0x23, 0xdf, 0xf9, 0xb8, 0x0f, 0xf0, 0x6d, 0x59, 0x95, 0x6a, 0xef, 0x2b, 0x08,
	0xbb, 0x55, 0x42, 0xdb, 0x24, 0x1c, 0x52, 0xc6, 0x48, 0xb6, 0x74, 0xe8, 0xbc, 0x7a, 0x3d, 0xbe,
	0x35, 0x7a, 0xa4, 0x52, 0x83, 0x77, 0x5d, 0x62, 0xe0, 0x2f, 0x6f, 0x75, 0xd7, 0xa5, 0x01, 0xfe,
	0x8e, 0x9a, 0xda, 0x76, 0x53, 0x76, 0x36, 0x26, 0x86, 0x8e, 0xf5, 0x2b, 0x53, 0x26, 0x82, 0xea,
	0x98, 0xd4, 0x5b, 0x69, 0x74, 0x5e, 0xea, 0xbd, 0xfc, 0x54, 0x6f, 0x86, 0x7f, 0x7a, 0x34, 0x0d,
	0xe2, 0x45, 0x48, 0xd0, 0x89, 0xea, 0x13, 0xbd, 0xa2, 0x0b, 0x5d, 0xfb, 0xb8, 0x55, 0xda, 0xcd,
	0x66, 0xad, 0xdd, 0xfc, 0x46, 0xd3, 0xf0, 0x4f, 0xff, 0x0e, 0x1a, 0x34, 0x50, 0xad, 0xac, 0x67,
	0xb6, 0xb2, 0xff, 0xcd, 0xea, 0x2f, 0x95, 0xcd, 0xfb, 0xce, 0x1d, 0x34, 0x5d, 0x60, 0x15, 0xf1,
	0xbc, 0xe7, 0xfc, 0xc4, 0xe7, 0x6a, 0x5b, 0xfc, 0x99, 0x7c, 0xf7, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0xe1, 0xee, 0x12, 0xa6, 0x0c, 0x00, 0x00,
}
