// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/cmd.proto

package msg

type Hall_C_Msg struct {
	Token string `json:"token"`
}

//type GameInfo struct {
//	GameID         int32       `json:"game_id"`
//	KindID         int32       `json:"kind_id"`
//	ServerAddr     string      `json:"server_addr"`
//	WsAddr         string      `json:"ws_addr"`
//	GameName       string      `json:"game_name"`
//	SortID         int32       `json:"sort_id"`
//	TableCount     int32       `json:"table_count"`
//	ChairCount     int32       `json:"chair_count"`
//	CellScore      float32     `json:"cell_score"`
//	RevenueRatio   float32     `json:"revenue_ratio"`
//	MinEnterScore  float32     `json:"minEnter_score"`
//	DeductionsType int32       `json:"deductions_type"`
//	GameVersion    int         `json:"game_version"`
//	GameStatus     int         `json:"game_status"`
//	RoomInfo       []*RoomInfo `json:"game_room"`
//}
//
//type Announcement struct {
//	NewsID        int32  `json:"news_id"`
//	Subject       string `json:"subject"`
//	Body          string `json:"body"`
//	FormattedBody string `json:"formatted_body"`
//	ClassID       int32  `json:"class_id"`
//}
//
////成功+心跳
//type Hall_S_Msg struct {
//	UserID           int32           `json:"user_id"`
//	NikeName         string          `json:"nike_name"`
//	MemberOrder      int32           `json:"member_order"`
//	PhoneNumber      string          `json:"phone_number"`
//	BinderCardNo     string          `json:"binder_card_no"`
//	FaceID           int32           `json:"face_id"`
//	RoleID           int32           `json:"role_id"`
//	SuitID           int32           `json:"suit_id"`
//	PhotoFrameID     int32           `json:"photo_frame_id"`
//	Gender           int32           `json:"gender"`
//	TimeStamp        int64           `json:"time_stamp"`
//	AnnouncementList []*Announcement `json:"announcement_list"`
//	GameInfoList     []*GameInfo     `json:"game_info_list"`
//	VersionInfos     []*VersionInfo  `json:"version_infos"`
//	UserGold         float32         `json:"user_gold"`
//	UserDiamonds     float32         `json:"user_diamonds"`
//}
//
//// 版本信息 xjplatformdb.GameVersion
//type VersionInfo struct {
//	Version   int32  `json:"version"`
//	PokerName string `json:"poker_name"`
//}
//
////充值通知
//type Hall_Recharge_Notice struct {
//	UserGold     float32 `json:"user_gold"`
//	UserDiamonds float32 `json:"user_diamonds"`
//}

//失败
type Hall_S_Fail struct {
	ErrorCode int32  `json:"error_code"`
	ErrorMsg  string `json:"error_msg"`
}

//type GameInfo struct {
//	game_name string `json:"game_name"`
//	game_id int `json:"game_id"`
//	game_version int `json:"game_version"`
//	game_status int `json:"game_status"`
//
//}

//新的结构体
// 登录心跳后的初始化通知
type HeartLoginInit struct {
	GameInfo []*GameInfo `json:"game_info"`
	UserInfo *UserInfo   `json:"user_info"`
	Notify   []*Notify   `json:"notify"`
	SendTime string      `json:"send_time"`
}

type GameInfo struct {
	GameName    string      `json:"game_name"`    // 游戏名字
	KindId      int32       `json:"kind_id"`      // 游戏ID
	GameVersion int32       `json:"game_version"` // 游戏版本号
	GameStatus  int32       `json:"game_status"`  // 游戏状态（0：关闭/1：开启）
	RoomInfo    []*RoomInfo `json:"game_room"`
}

// 房间信息
type RoomInfo struct {
	RoomServer string  `json:"room_server"` // 房间地址
	RoomStatus int32   `json:"room_status"` // 房间状态（0：关闭/1：开启）
	GameID     int32   `json:"game_id"`     // 游戏房间ID
	SortID     int32   `json:"sort_id"`     // 排序ID
	CellScore  float32 `json:"cell_score"`  // 游戏底分
	EnterScore float32 `json:"enter_score"` // 最低进入低分
	ScoreType  int32   `json:"score_type"`  // 扣分类型
}

// 玩家信息变更通知
type UserInfoChange struct {
	UserInfo *UserInfo `json:"user_info"`
	SendTime string    `json:"send_time"`
}

//房间信息变更通知
type GameInfoChange struct {
	GameInfo []*GameInfo `json:"game_info"`
}

type UserInfo struct {
	Gold    float64 `json:"gold"`    // 金币
	Diamond float64 `json:"diamond"` // 余额
}

// 通知
type Notify struct {
	Code int    `json:"code"` // 通知类型（1：充值到账 2：提现到账      901：系统维护 902：强制踢下线 903：异地登录）
	Msg  string `json:"msg"`  // 通知内容
}
