// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg/cmd.proto

package msg

//登陆消息
type Game_C_TokenLogin struct {
	Token     string `json:"token"`
	MachineID string `json:"machine_id"`
}

//机器人登陆
type Game_C_RobotLogin struct {
	UserID  int32 `json:"user_id"`
	BatchID int32 `json:"batch_id"`
}

//用户坐下
type Game_C_UserSitDown struct {
}

//用户起立
type Game_C_UserStandUp struct {
}

//用户抢庄
type Game_C_UserQZ struct {
	Multiple int32 `json:"multiple"`
}

//用户下注
type Game_C_UserJetton struct {
	Multiple int32 `json:"multiple"`
}

//用户摊牌
type Game_C_UserTP struct {
}

//请求失败
type Game_S_ReqlyFail struct {
	ErrorCode int32  `json:"errno"`
	ErrorMsg  string `json:"errmsg"`
}

//登陆成功
type Game_S_LoginSuccess struct {
	GameQZTime     int32 `json:"call_round_time"` // 抢庄环节时间
	GameStartTime  int32 `json:"card_round_time"` // 发牌下注环节时间 开始游戏
	GameTPTime     int32 `json:"show_round_time"` // 开牌环节时间
	GameJettonTime int32 `json:"bet_round_time"`  //  叫倍环节时间
	//MultipleList   []int32 `json:"multiple_list"`   //抢庄倍数
	//JettonList     []int32 `json:"jetton_list"`     //下注倍数
	Status int32 `json:"reconnect"` //是否重连（0：是/1：不是）
}

//坐下通知消息
type Game_S_SitDownNotify struct {
	TableID int32         `json:"table_id"`
	Data    []Game_S_User `json:"user_list"` // 椅子号 用户信息
}

//user
type Game_S_User struct {
	UserID       int32   `json:"user_id"`
	NikeName     string  `json:"user_nickname"`
	UserGold     float32 `json:"user_gold"`
	UserDiamond  float32 `json:"user_diamond"`
	MemberOrder  int32   `json:"user_vip_level"` //会员等级
	HeadImageUrl string  `json:"user_head_url"`  // 头像
	FaceID       int32   `json:"face_id"`
	RoleID       int32   `json:"user_model"` // accounts_image.RoleID 角色标识（客户端数据，从1开始）
	//	SuitID       int32   `json:"suit_id"`
	PhotoFrameID int32 `json:"user_head_frame"` //  头像框
	TableID      int32 `json:"table_id"`
	ChairID      int32 `json:"chair_id"` //椅子号
	//Status       int32   `json:"status"`
	//Gender       int32   `json:"gender"`
}

//起立通知消息
type Game_S_StandUpNotify struct {
	ChairID int32 `json:"chair_id"`
}

//掉线通知消息
type Game_S_OffLineNotify struct {
	ChairID int32 `json:"chair_id"`
}

//上线通知消息
type Game_S_OnLineNotify struct {
	ChairID int32 `json:"chair_id"`
}

//空闲场景发牌
type Game_S_FreeScene struct {
	SceneStartTime int64         `json:"surplus_time"`
	TableID        int32         `json:"table_id"`  // 桌子ID
	UserChairID    int32         `json:"chair_id"`  // 椅子ID
	UserList       []Game_S_User `json:"user_list"` // 玩家列表
}

//抢庄场景
type Game_S_QZScene struct {
	SceneStartTime int64           `json:"surplus_time"` //1
	UserChairID    int32           `json:"chair_id"`     //3
	UserList       []Game_S_User   `json:"user_list"`    //4
	TableID        int32           `json:"table_id"`     //2
	Multiple       []int32         `json:"multiple"`     //5  可抢倍数,动态
	UserListQZ     []Game_S_UserQZ `json:"call_list"`    //6  已抢情况
	//UserPlaying    map[int32]bool         `json:"user_playing"` //开始游戏玩家
	RecordID string `json:"record_id"` // 局号
}

//下注场景叫倍场景
type Game_S_JettonScene struct {
	SceneStartTime int64               `json:"surplus_time"`    // 1
	UserChairID    int32               `json:"chair_id"`        // 3
	UserList       []Game_S_User       `json:"user_list"`       //4
	UserListJetton []Game_S_UserJetton `json:"bet_list"`        // 7.已叫情况
	BankerChairID  int32               `json:"banker"`          //5
	TableID        int32               `json:"table_id"`        //3
	Multiple       []int32             `json:"multiple"`        // 6 可以下注倍数
	BankerMultiple int32               `json:"banker_multiple"` // 8.庄家倍数
	UserPlaying    map[int32]bool      `json:"user_playing"`
	RecordID       string              `json:"record_id"` // 局号
}

//摊牌场景
type Game_S_TPScene struct {
	SceneStartTime int64               `json:"surplus_time"`    //1
	TableID        int32               `json:"table_id"`        //2
	UserChairID    int32               `json:"chair_id"`        //3
	UserList       []Game_S_User       `json:"user_list" `      //4
	UserListTP     []Game_S_UserTP     `json:"show_list"`       // 7开牌情况 //改成数组
	BankerChairID  int32               `json:"banker"`          //5
	UserListJetton []Game_S_UserJetton `json:"bet_list"`        // 叫倍情况 key 椅子id
	BankerMultiple int32               `json:"banker_multiple"` //庄家倍数
	RecordID       string              `json:"record_id"`       // 局号
	//UserPlaying    map[int32]bool                 `json:"user_playing"`
}

type Game_S_LotteryPoker struct {
	PokerType    int32   `json:"card_type"`
	LotteryPoker []int32 `json:"lottery_poker"`
}

//
////开始定时器
//type Game_S_StartTime struct {
//	GameStatus  int32          `json:"game_status"`
//	UserPlaying map[int32]bool `json:"user_playing"`
//}

//开始定时器发牌环节
type Game_S_CardRound struct {
	RecordID string `json:"record_id"` // 局号
}

// 抢庄环节（可抢庄倍数配置）
type Game_S_CallRound struct {
	Multiple []int32 `json:"multiple"`
}

// 叫倍环节（可叫倍数配置）
type Game_S_BetRound struct {
	Multiple []int32 `json:"multiple"`
}

// 开牌环节
type Game_S_ShowRound struct {
}

//结束游戏消息
type Game_S_GameConclude struct {
	ResultList []Game_S_GameResult `json:"result_list"`
	//UserListLoss map[int32]float32 `json:"result_list"`
	//UserListMoney map[int32]float32 `json:"user_list_money"`
}

// 结束游戏
type Game_S_GameResult struct {
	ChairID int32   `json:"chair_id"`
	Result  float32 `json:"result"`
}

//抢庄通知
type Game_S_UserQZ struct {
	ChairID  int32 `json:"chair_id"`
	Multiple int32 `json:"multiple"`
}

//定庄通知
type Game_S_GameDZ struct {
	ChairID  int32 `json:"chair_id"`
	Multiple int32 `json:"multiple"`
}

//下注通知  叫倍通知
type Game_S_UserJetton struct {
	ChairID  int32 `json:"chair_id"`
	Multiple int32 `json:"multiple"`
}

//摊牌通知  开牌通知
type Game_S_UserTP struct {
	ChairID      int32   `json:"chair_id"`
	PokerType    int32   `json:"type"`
	LotteryPoker []int32 `json:"card"`
	//Poker   *Game_S_LotteryPoker `json:"card"`
}

// 发牌通知
type Game_S_GameCard struct {
	ChairID      int32   `json:"chair_id"`
	PokerType    int32   `json:"type"`
	LotteryPoker []int32 `json:"card"`
	//Poker   *Game_S_LotteryPoker `json:"card"`
}
